### ISSUE TITLE
Crash when using `Consolas` font on Windows

### ISSUE THREAD

**Issue by andrewvaughanj** [wez/wezterm#1042]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20210817-220027-4fc8dfb

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using an alternative font configuration on Windows (see my `wezterm.lua` below) and sending a lot of binary data "by mistake" (I'm emulating this with `dd if=/dev/urandom bs=1MB count=1`), `wezterm` crashes.

This appears for me on both the latest binary release and also a local build (such that I can do `export RUST_BACKTRACE=full`).

### To Reproduce

- Configure your `wezterm.lua` as above
- ssh to a Linux host
- run `dd if=/dev/urandom bs=1MB count=1`
- obtain crash

### Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font_with_fallback({
     "Consolas",
     "JetBrains Mono",
  }),
}
```

### Expected Behavior

Ideally, for `wezterm` not to crash 😸 

### Logs

```
thread 'main' panicked at 'capacity overflow', library\alloc\src\raw_vec.rs:560:5
stack backtrace:
   0:     0x7ff75dcea1bf - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff75dcea1bf - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff75dcea1bf - std::sys_common::backtrace::_print_fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:67
   3:     0x7ff75dcea1bf - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:46
   4:     0x7ff75dd07e4a - core::fmt::write
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\fmt\mod.rs:1110
   5:     0x7ff75dce1858 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\io\mod.rs:1588
   6:     0x7ff75dcecf86 - std::sys_common::backtrace::_print
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:49
   7:     0x7ff75dcecf86 - std::sys_common::backtrace::print
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:36
   8:     0x7ff75dcecf86 - std::panicking::default_hook::{{closure}}
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:208
   9:     0x7ff75dceca69 - std::panicking::default_hook
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:225
  10:     0x7ff75dced710 - std::panicking::rust_panic_with_hook
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:626
  11:     0x7ff75dced1a3 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:517
  12:     0x7ff75dceab0f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\sys_common\backtrace.rs:141
  13:     0x7ff75dced129 - std::panicking::begin_panic_handler
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:515
  14:     0x7ff75e03aa40 - core::panicking::panic_fmt
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:92
  15:     0x7ff75e03a98c - core::panicking::panic
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\core\src\panicking.rs:50
  16:     0x7ff75dcfedbc - alloc::raw_vec::capacity_overflow
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\alloc\src\raw_vec.rs:560
  17:     0x7ff75d61f18f - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::he3d8d1f03d62c4eb
  18:     0x7ff75d61e56c - resize::Scale::new::hf963462e643d37ee
  19:     0x7ff75d5a8c93 - window::bitmaps::Image::resize::hfaafc315e65f4e18
  20:     0x7ff75d5a8f2c - window::bitmaps::Image::scale_by::hdbcdfee7ad5da379
  21:     0x7ff75d1e758d - wezterm_gui::glyphcache::GlyphCache<T>::cached_glyph::he386f267f165f1c2
  22:     0x7ff75d178f89 - wezterm_gui::termwindow::clipboard::<impl wezterm_gui::termwindow::TermWindow>::copy_to_clipboard::h8ac4f926d177e81f
  23:     0x7ff75d173a8e - wezterm_gui::termwindow::clipboard::<impl wezterm_gui::termwindow::TermWindow>::copy_to_clipboard::h8ac4f926d177e81f
  24:     0x7ff75d184bb6 - wezterm_gui::termwindow::TermWindow::dispatch_window_event::h6bd6b6890606a2de
  25:     0x7ff75d1ccd96 - wezterm_gui::termwindow::TermWindow::new_window::{{closure}}::{{closure}}::h6fb33a5c297b9355
  26:     0x7ff75d5ac1fc - window::os::windows::window::wm_paint::h35b63d9905c1cfb2
  27:     0x7ff75d5ad7b1 - window::os::windows::window::do_wnd_proc::hade12b94bb6ca657
  28:     0x7ff75d5b142d - window::os::windows::window::do_wnd_proc::hade12b94bb6ca657
  29:     0x7ffce78b5c1d - CallWindowProcW
  30:     0x7ffce78b57ec - DispatchMessageW
  31:     0x7ffce78c1f83 - IsWindowVisible
  32:     0x7ffce87a0c14 - KiUserCallbackDispatcher
  33:     0x7ffce5be1764 - NtUserDispatchMessage
  34:     0x7ffce78b56fc - DispatchMessageW
  35:     0x7ff75d5a43fa - <window::os::windows::connection::Connection as window::connection::ConnectionOps>::run_message_loop::h0baf2886468da18a
  36:     0x7ff75d23b0aa - wezterm_gui::terminate_with_error::h4d9265339d44dbdb
  37:     0x7ff75d237a61 - wezterm_gui::terminate_with_error::h4d9265339d44dbdb
  38:     0x7ff75d2272c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf8b8070c10fc5045
  39:     0x7ff75d210f0c - std::rt::lang_start::{{closure}}::ha4b94375cf3d0d55
  40:     0x7ff75dcedb3a - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\ops\function.rs:280
  41:     0x7ff75dcedb3a - std::panicking::try::do_call
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:401
  42:     0x7ff75dcedb3a - std::panicking::try
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panicking.rs:365
  43:     0x7ff75dcedb3a - std::panic::catch_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\panic.rs:434
  44:     0x7ff75dcedb3a - std::rt::lang_start_internal
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\/library\std\src\rt.rs:34
  45:     0x7ff75d240657 - main
  46:     0x7ff75dfc6e50 - invoke_main
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  47:     0x7ff75dfc6e50 - __scrt_common_main_seh
                               at D:\a01\_work\26\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  48:     0x7ffce7cf7c24 - BaseThreadInitThunk
  49:     0x7ffce876d721 - RtlUserThreadStart
 2021-08-18T11:11:42.650Z ERROR window::os::windows::window            > caught Any { .. }
```

**Comment by wez** [comment]
Can you set `WEZTERM_LOG=wezterm_gui::glyphcache=trace,info` in the environment and then run wezterm?
I'm hoping to see a log line like:

`physically scaling ...`

FWIW, it looks like the overflow is happening inside the image crate in the case where a glyph is large; that log line should give an indicate of whether were passing in crazy values or not

**Comment by andrewvaughanj** [comment]
[log.txt](https://github.com/wez/wezterm/files/7007965/log.txt)

Log against master is attached!

**Comment by wez** [comment]
```
2021-08-18T14:29:50.258Z TRACE wezterm_gui::glyphcache                > physically scaling GlyphInfo { is_space: false, cluster: 50, num_cells: 0, font_idx: 0, glyph_pos: 2575, x_advance: 20.0, y_advance: 0.0, x_offset: 0.0, y_offset: 0.0 } by inf bcos 20x22 > 20.0x42.15234375. aspect=0.4744694652951534
```

scaling by `inf` seems a bit... optimistic!

**Comment by wez** [comment]
I've pushed a commit that should avoid the divide by zero; please give it a try!

**Comment by andrewvaughanj** [comment]
Gave it a try -- my reproducible steps no longer reproduce a crash!

I'd guess this means your fix worked 🥳 

Want me to close this issue?

**Comment by wez** [comment]
I'll write up a changelog entry and close it; thanks for confirming!
