### ISSUE TITLE
[crash] thread 'main' panicked at '`at` split index (is 191) should be <= len (is 190)', library/alloc/src/vec/mod.rs:1945:13

### ISSUE THREAD

**Issue by Lenbok** [wez/wezterm#2355]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

Windowmaker / compiz

### WezTerm version

wezterm 20220802-182149-33866dad (nightly) and 20220802-215653-1df1f166 (from source)

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

(The above was built from source, after experiencing the same problem with the nightlies.)

Fairly frequently, wezterm will just crash out on me, with the following

```
08:53:14.220  ERROR  env_bootstrap          > panic at library/alloc/src/vec/mod.rs:1945:13 - !?
   0: env_bootstrap::register_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   6: alloc::vec::Vec<T,A>::split_off::assert_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/vec/mod.rs:1945:13
   7: termwiz::surface::line::line::Line::split_off
   8: mux::pane::LogicalLine::apply_hyperlink_rules
   9: mux::pane::Pane::get_lines_with_hyperlinks_applied
  10: wezterm_gui::termwindow::render::<impl wezterm_gui::termwindow::TermWindow>::paint_opengl_pass
  11: wezterm_gui::termwindow::TermWindow::dispatch_window_event
  12: wezterm_gui::termwindow::TermWindow::new_window::{{closure}}::{{closure}}
  13: window::os::x11::window::XWindowInner::dispatch_pending_events
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: async_task::raw::RawTask<F,T,S>::run
  16: window::spawn::SpawnQueue::run
  17: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
  18: wezterm_gui::main
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
  20: std::rt::lang_start::{{closure}}
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/rt.rs:128:20
  22: main
  23: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  24: _start

thread 'main' panicked at '`at` split index (is 191) should be <= len (is 190)', library/alloc/src/vec/mod.rs:1945:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### To Reproduce

I have not yet found a way to reproduce.

### Configuration

```
local wezterm = require("wezterm");

local hostname = wezterm.hostname();
local irows = 55;
local icols = 191;
if hostname == "noir" then
   irows = 65;
   icols = 191;
end

-- Powerline dividers
local SOLID_RIGHT_ARROW = utf8.char(0xe0b0); -- The  symbol
local RIGHT_ARROW = utf8.char(0xe0b1);       -- The  symbol
local SOLID_LEFT_ARROW = utf8.char(0xe0b2);  -- The  symbol
local LEFT_ARROW = utf8.char(0xe0b3);        -- The  symbol

-- Foreground color for the text across the tabs
local tab_text_fg = "#000000";
-- Color of the empty space in the middle of the status bar
local tab_empty_bg = "#000000";

-- Color palette for the backgrounds of right status tab cells
local tab_segment_colors = {
  "#ffff00",
  "#cccc00",
  "#aaaa00",
  "#777700",
};

-- An alternate palette
-- local tab_text_fg = "#c0c0c0";
-- local tab_segment_colors = {
--   "#b491c8",
--   "#7c5295",
--   "#663a82",
--   "#52307c",
--   "#3c1361",
-- };

wezterm.on("toggle-ligature", function(window, pane)
  local overrides = window:get_config_overrides() or {}
  if not overrides.harfbuzz_features then
    -- If we haven't overridden it yet, then override with ligatures disabled
    overrides.harfbuzz_features =  {"calt=0", "clig=0", "liga=0"}
  else
    -- else we did already, and we should disable out override now
    overrides.harfbuzz_features = nil
  end
  window:set_config_overrides(overrides)
end)



wezterm.on("format-tab-title", function(tab, tabs, panes, config, hover, max_width)
  local edge_background = "#0b0022"
  local background = "#005500"
  local foreground = tab_text_fg

  if tab.is_active then
    background = "#00cc00"
  elseif hover then
    background = "#008800"
  end

  local edge_foreground = background

  -- ensure that the titles plus decorations fit in the available space,
  -- and that we have room for the edges.
  local title = wezterm.truncate_right(tab.active_pane.title, max_width-5)
  local elements = {};
  if tab.tab_index > 0 then
     table.insert(elements, {Background={Color=edge_foreground}});
     table.insert(elements, {Foreground={Color=edge_background}});
     table.insert(elements, {Text=SOLID_RIGHT_ARROW});
  else
     table.insert(elements, {Text=" "});
  end
  table.insert(elements, {Background={Color=background}});
  table.insert(elements, {Foreground={Color=foreground}});
  table.insert(elements, {Text=(tab.tab_index + 1) .. "›" .. title .. " "});
  table.insert(elements, {Background={Color=edge_background}});
  table.insert(elements, {Foreground={Color=edge_foreground}});
  table.insert(elements, {Text=SOLID_RIGHT_ARROW});
  return elements;
end)

wezterm.on("update-right-status", function(window, pane)
  -- Each element holds the text for a cell
  local cells = {};

  -- Show which key table is active in status area
  -- local tablename = window:active_key_table();
  -- table.insert(cells, tablename or "no table");

  -- Figure out the cwd and host of the current pane.
  -- This will pick up the hostname for the remote host if your
  -- shell is using OSC 7 on the remote host.
  local cwd_uri = pane:get_current_working_dir()
  if cwd_uri then
    cwd_uri = cwd_uri:sub(8);
    local slash = cwd_uri:find("/")
    local cwd = ""
    local hostname = ""
    if slash then
      hostname = cwd_uri:sub(1, slash-1)
      -- Remove the domain name portion of the hostname
      local dot = hostname:find("[.]")
      if dot then
        hostname = hostname:sub(1, dot-1)
      end
      -- and extract the cwd from the uri
      cwd = cwd_uri:sub(slash)

      table.insert(cells, cwd);
      -- table.insert(cells, hostname);
    end
  end

  -- Show which workspace is active in status area
  local domain = pane:get_domain_name();
  local workspacename = window:active_workspace();
  table.insert(cells, string.upper(domain) .. "[" .. string.upper(workspacename) .. "]");

  -- I like my date/time in this style: "Wed Mar 3 08:14"
  local date = wezterm.strftime("%a %Y-%m-%d %H:%M");
  table.insert(cells, date);

  -- The elements to be formatted
  local elements = {};
  local total_cells = #cells; -- How many cells to format
  local num_cells = 0;        -- How many cells have been formatted

  -- Translate a cell into elements in a "powerline" style << fade
  function push(text, is_last)
    local segment_color_idx = total_cells - num_cells
    if num_cells == 0 then
      table.insert(elements, {Foreground={Color=tab_segment_colors[segment_color_idx]}})
      table.insert(elements, {Text=LEFT_ARROW})
      table.insert(elements, {Text=SOLID_LEFT_ARROW})
    end
    table.insert(elements, {Foreground={Color=tab_text_fg}})
    table.insert(elements, {Background={Color=tab_segment_colors[segment_color_idx]}})
    table.insert(elements, {Text=" "..text.." "})
    if not is_last then
      table.insert(elements, {Foreground={Color=tab_segment_colors[segment_color_idx - 1]}})
      table.insert(elements, {Text=SOLID_LEFT_ARROW})
    end
    num_cells = num_cells + 1
  end

  if window:leader_is_active() then
      table.insert(elements, {Background={Color=tab_empty_bg}})
      table.insert(elements, {Foreground={Color="#0000ff"}})
      table.insert(elements, {Text=SOLID_LEFT_ARROW})
      table.insert(elements, {Background={Color="#0000ff"}})
      table.insert(elements, {Foreground={Color="#ffffff"}})
      table.insert(elements, {Text=" ` "})
      table.insert(elements, {Foreground={Color=tab_empty_bg}})
      table.insert(elements, {Text=SOLID_LEFT_ARROW})
  end
  table.insert(elements, {Background={Color=tab_empty_bg}})
  while #cells > 0 do
    local cell = table.remove(cells, 1)
    push(cell, #cells == 0)
  end

  window:set_right_status(wezterm.format(elements));
end);


return {

   -- default_gui_startup_args = {"connect", "localhost"},
   unix_domains = {
      {
         name = "localhost",
      },
      -- Try using this workaround to permit port forwarding.
      -- wezterm native ssh domains do not permit this.
      -- However, this doesn't help determine the appropriate DISPLAY variable
      {
         name = "hardhead",
         proxy_command = {"ssh", "-T", "hardhead", "wezterm-cli-proxy"},
      },
      {
         name = "noir",
         proxy_command = {"ssh", "-T", "noir", "wezterm-cli-proxy"},
      },
      {
         name = "tron",
         proxy_command = {"ssh", "-T", "tron", "wezterm-cli-proxy"},
      },
   },

   ssh_domains = {
      -- All we really need is remote_address, other configuration (usernames etc) is in ~/.ssh/config
      -- Note that built-in ssh domain doesn't support port forwarding.
      {
         name = "noir-w",
         remote_address = "noir",
         local_echo_threshold_ms = 100,
      },
      {
         name = "tron-w",
         remote_address = "tron",
         local_echo_threshold_ms = 100,
      },
      {
         name = "hardhead-w",
         remote_address = "hardhead",
         local_echo_threshold_ms = 100,
      },
   },

   --
   -- Behavior
   --

   check_for_updates = false,
   disable_default_key_bindings = true,
   exit_behavior = "Close",

   enable_tab_bar = true,  -- false when using tmux, true for wezterm multiplexing

   leader = { key = "`", timeout_milliseconds = 2000}, -- use this when you're not using tmux. Add mods = "CTRL" to disable if using tmux
   keys = {
      -- Send "`" key to the terminal when pressed after LEADER
      { key = "`", mods = "LEADER",       action = wezterm.action{SendString = "`"}},
      { key = "-", mods = "LEADER",       action = wezterm.action{SplitVertical = {domain = "CurrentPaneDomain"}}},
      { key = "\\",mods = "LEADER",       action = wezterm.action{SplitHorizontal = {domain = "CurrentPaneDomain"}}},
      { key = "c", mods = "LEADER",       action = wezterm.action{SpawnTab = "CurrentPaneDomain"}},
      { key = "h", mods = "LEADER",       action = wezterm.action{SplitPane = {direction="Up", command = {domain = "CurrentPaneDomain", args = {"htop"}}}}},
      { key = "l", mods = "LEADER",       action = wezterm.action{EmitEvent = "toggle-ligature"}},
      { key = "\t",mods = "LEADER",       action = "ActivateLastTab"},
      { key = "1", mods = "LEADER",       action = wezterm.action{ActivateTab = 0}},
      { key = "2", mods = "LEADER",       action = wezterm.action{ActivateTab = 1}},
      { key = "3", mods = "LEADER",       action = wezterm.action{ActivateTab = 2}},
      { key = "4", mods = "LEADER",       action = wezterm.action{ActivateTab = 3}},
      { key = "5", mods = "LEADER",       action = wezterm.action{ActivateTab = 4}},
      { key = "6", mods = "LEADER",       action = wezterm.action{ActivateTab = 5}},
      { key = "7", mods = "LEADER",       action = wezterm.action{ActivateTab = 6}},
      { key = "8", mods = "LEADER",       action = wezterm.action{ActivateTab = 7}},
      { key = "9", mods = "LEADER",       action = wezterm.action{ActivateTab = 8}},
      { key = "n", mods = "LEADER",       action = wezterm.action{ActivateTabRelative = 1}},
      { key = "p", mods = "LEADER",       action = wezterm.action{ActivateTabRelative = -1}},
      { key = "<", mods = "LEADER|SHIFT", action = wezterm.action{MoveTabRelative = -1}},
      { key = ">", mods = "LEADER|SHIFT", action = wezterm.action{MoveTabRelative = 1}},

      { key = "z", mods = "LEADER",       action = "TogglePaneZoomState"},

      { key = " ", mods = "LEADER",       action = "ShowLauncher"},
      { key = " ", mods = "LEADER|CTRL",       action = wezterm.action{ShowLauncherArgs = {flags = "FUZZY|DOMAINS|WORKSPACES|TABS|LAUNCH_MENU_ITEMS|KEY_ASSIGNMENTS"}}},
      -- { key = " ", mods = "LEADER",       action = wezterm.action{ShowLauncherArgs = {flags = "FUZZY"}}},

      { key = "&", mods = "LEADER|SHIFT", action = wezterm.action{CloseCurrentTab = {confirm = true}}},
      { key = "x", mods = "LEADER",       action = wezterm.action{CloseCurrentPane = {confirm = true}}},
      { key = "w", mods = "LEADER",       action = "ShowTabNavigator"},

      { key = "s", mods = "LEADER",       action = wezterm.action{ShowLauncherArgs = {title = "Workspaces", flags = "FUZZY|WORKSPACES"}}},
      -- Experimental, associate workspace with remote domain, see https://github.com/wez/wezterm/issues/1874
      { key = "d", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {name = "default"}}},
      { key = "h", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {name = "HOME",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "tron"
                                                                        }
                                                                     }
      }}},
      { key = "w", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {name = "WORK",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "noir"
                                                                        }
                                                                     }
      }}},
      { key = "r", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {
                                                                     name = "RTG",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "noir"
                                                                        }
                                                                     }
      }}},
      { key = "s", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {
                                                                     name = "SAREPTA",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "noir"
                                                                        }
                                                                     }
      }}},
      { key = "t", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {
                                                                     name = "TEMPUS",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "noir"
                                                                        }
                                                                     }
      }}},
      { key = "l", mods = "LEADER|SHIFT",       action = wezterm.action{SwitchToWorkspace = {
                                                                     name = "LIC",
                                                                     spawn = {
                                                                        domain = {
                                                                           DomainName = "hardhead"
                                                                        }
                                                                     }
      }}},

      { key = "s", mods = "LEADER|CTRL",  action = wezterm.action{Search = {CaseInSensitiveString=""}}},

      { key = "y", mods = "LEADER|CTRL",   action = wezterm.action{PasteFrom = "PrimarySelection"}},

      { key = "'", mods = "LEADER",       action = "QuickSelect"},
      { key = "'", mods = "LEADER|ALT",   action = "QuickSelect"},

      { key = "[", mods = "LEADER",       action = "ActivateCopyMode"},
   },

   key_tables = {
      -- Emacs-ish bindings in copy mode
      copy_mode = {
         { key = "Escape", mods = "NONE", action = wezterm.action{CopyMode = "Close"}},
         { key = "g", mods = "CTRL", action = wezterm.action{CopyMode = "Close"}},
         { key = "'", mods = "ALT",  action = "QuickSelect"},

         { key = "b", mods = "CTRL", action = wezterm.action{CopyMode = "MoveLeft"}},
         { key = "f", mods = "CTRL", action = wezterm.action{CopyMode = "MoveRight"}},
         { key = "p", mods = "CTRL", action = wezterm.action{CopyMode = "MoveUp"}},
         { key = "n", mods = "CTRL", action = wezterm.action{CopyMode = "MoveDown"}},
         { key = "b", mods = "ALT",  action = wezterm.action{CopyMode = "MoveBackwardWord"}},
         { key = "f", mods = "ALT",  action = wezterm.action{CopyMode = "MoveForwardWord"}},
         { key = "a", mods = "CTRL", action = wezterm.action{CopyMode = "MoveToStartOfLine"}},
         { key = "e", mods = "CTRL", action = wezterm.action{CopyMode = "MoveToEndOfLineContent"}},
         { key = "m", mods = "ALT",  action = wezterm.action{CopyMode = "MoveToStartOfLineContent"}},
         { key = "v", mods = "CTRL", action = wezterm.action{CopyMode = "PageDown"}},
         { key = "v", mods = "ALT",  action = wezterm.action{CopyMode = "PageUp"}},
         { key = "<", mods = "ALT|SHIFT", action = wezterm.action{CopyMode = "MoveToScrollbackTop"}},
         { key = ">", mods = "ALT|SHIFT", action = wezterm.action{CopyMode = "MoveToScrollbackBottom"}},
         { key = " ", mods = "CTRL", action = wezterm.action{CopyMode = {SetSelectionMode = "Cell"}}},
         { key = "s", mods = "CTRL", action = wezterm.action{Search = {CaseInSensitiveString=""}}},
         { key = "r", mods = "CTRL", action = wezterm.action{Search = {CaseInSensitiveString=""}}},
         { key = "w", mods = "ALT",  action = wezterm.action{Multiple = {
              wezterm.action{CopyTo = "ClipboardAndPrimarySelection"},
              wezterm.action{CopyMode = "Close"},
         }}},
      },
      search_mode = {
         { key = "Escape", mods = "NONE", action = wezterm.action{Multiple = {
              wezterm.action{CopyMode = "ClearPattern"},
              wezterm.action{CopyMode = "Close"},
         }}},
         { key = "g", mods = "CTRL", action = wezterm.action{Multiple = {
              wezterm.action{CopyMode = "ClearPattern"},
              wezterm.action{CopyMode = "Close"},
         }}},
         { key = "'", mods = "ALT",  action = "QuickSelect"},
         { key = "Enter", mods = "NONE", action = wezterm.action{CopyMode = "Close"}},
         { key = "s", mods = "CTRL", action = wezterm.action{CopyMode = "NextMatch"}},
         { key = "r", mods = "CTRL", action = wezterm.action{CopyMode = "PriorMatch"}},
         { key = "n", mods = "CTRL", action = wezterm.action{CopyMode = "NextMatch"}},
         { key = "p", mods = "CTRL", action = wezterm.action{CopyMode = "PriorMatch"}},
         { key = "DownArrow", mods = "NONE", action = wezterm.action{CopyMode = "NextMatch"}},
         { key = "UpArrow", mods = "NONE", action = wezterm.action{CopyMode = "PriorMatch"}},
         { key = "PageDown", mods = "NONE", action = wezterm.action{CopyMode = "NextMatchPage"}},
         { key = "PageUp", mods = "NONE", action = wezterm.action{CopyMode = "PriorMatchPage"}},
         --{ key = "r", mods = "CTRL", action = wezterm.action{CopyMode = "CycleMatchType"}},
         { key = "u", mods = "CTRL", action = wezterm.action{CopyMode = "ClearPattern"}},
      },
   },

   enable_kitty_graphics = true,

   --
   -- Appearance
   --
   --font = wezterm.font("JetBrains Mono"),
   font = wezterm.font_with_fallback({
         "Hack FC Ligatured",
--         "Hack Nerd Font FC Ligatured"
   }),
   font_size = 12,

   initial_rows = irows,
   initial_cols = icols,

   tab_bar_at_bottom = true,
   window_padding = { left = 0, right = 0, bottom = 0, top = 0,},
   use_fancy_tab_bar = false,

   -- Appearance of "fancy" tab bar?
   window_frame = {
      inactive_titlebar_bg = "#111111",
      -- active_titlebar_bg = "#33aa55",
      -- inactive_tab_edge = "#ff4455",
   },

   -- Appearance of non-fancy tab bar
   colors = {
      selection_fg = "#cccccc",
      selection_bg = "#444488",

      tab_bar = {
         -- The color of the strip that goes along the top of the window
         -- (does not apply when fancy tab bar is in use)
         background = tab_empty_bg,
         active_tab = {bg_color = "#00cc00", fg_color = tab_text_fg,},
         inactive_tab = {bg_color = "#005500", fg_color = tab_text_fg,},
         inactive_tab_hover = {bg_color = "#008800", fg_color = tab_text_fg,},
         new_tab = {bg_color = "#999900", fg_color = tab_text_fg,},
         new_tab_hover = {bg_color = "#dddd00", fg_color = tab_text_fg,}
      }
   },
   tab_bar_style = {
    new_tab = ""
   },
}

```

### Expected Behavior

wezterm should not crash.

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.
