### ISSUE TITLE
"too many open files" on long running `wezterm ssh` session

### ISSUE THREAD

**Issue by bnoctis** [wez/wezterm#2466]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

wezterm 20220807-113146-c2fee766

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

On a long running `wezterm ssh` session, errors appear saying "Too many open files (os error 24)".

Not trying nightly because this requires a long wait period.

### Configuration

no config

### Logs

```
19:43:44.754  WARN   wezterm_ssh::pty                       > ssh: setenv TERM=xterm-256color failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.758  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM_VERSION=20220807-113146-c2fee766 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.762  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM=WezTerm failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.766  WARN   wezterm_ssh::pty                       > ssh: setenv COLORTERM=truecolor failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.770  WARN   wezterm_ssh::pty                       > ssh: setenv WEZTERM_REMOTE_PANE=56 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.773  ERROR  wezterm_gui::termwindow::spawn         > Failed to spawn: spawn_tab_or_window: Spawning in domain `SSH to devon`: TerminalSize { rows: 66, cols: 254, pixel_width: 3810, pixel_height: 1980, dpi: 144 } command=None cwd=None: failed to create a socketpair: Too many open files (os error 24)
19:43:44.927  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM=WezTerm failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.931  WARN   wezterm_ssh::pty                       > ssh: setenv WEZTERM_REMOTE_PANE=57 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.935  WARN   wezterm_ssh::pty                       > ssh: setenv COLORTERM=truecolor failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.938  WARN   wezterm_ssh::pty                       > ssh: setenv TERM=xterm-256color failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.941  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM_VERSION=20220807-113146-c2fee766 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:43:44.946  ERROR  wezterm_gui::termwindow::spawn         > Failed to spawn: spawn_tab_or_window: Spawning in domain `SSH to devon`: TerminalSize { rows: 66, cols: 254, pixel_width: 3810, pixel_height: 1980, dpi: 144 } command=None cwd=None: failed t19:50:39.020  WARN   wezterm_ssh::pty                       > ssh: setenv TERM=xterm-256color failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:50:39.025  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM_VERSION=20220807-113146-c2fee766 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:50:39.030  WARN   wezterm_ssh::pty                       > ssh: setenv COLORTERM=truecolor failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:50:39.033  WARN   wezterm_ssh::pty                       > ssh: setenv TERM_PROGRAM=WezTerm failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:50:39.037  WARN   wezterm_ssh::pty                       > ssh: setenv WEZTERM_REMOTE_PANE=58 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
19:50:39.050  ERROR  env_bootstrap                          > panic at mux/src/lib.rs:216:41 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Socketpair(Os { code: 24, kind: Uncategorized, message: "Too many open files" })', mux/src/lib.rs:216:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wez** [comment]
Do you create and destroy lots of panes/tabs/windows in that ssh session?

**Comment by bnoctis** [comment]
> Do you create and destroy lots of panes/tabs/windows in that ssh session?

Yes, tens of them I think

**Comment by wez** [comment]
I've pushed a commit that prevents a panic in this case, but doesn't address the underlying resource exhaustion

**Comment by wez** [comment]
When you close/destroy the tabs/panes, how do you do it? via CTRL-D/EOF or via a wezterm action to kill it?

**Comment by bnoctis** [comment]
> When you close/destroy the tabs/panes, how do you do it? via CTRL-D/EOF or via a wezterm action to kill it?

The latter, CloseCurrentPane

**Comment by wez** [comment]
This should be fixed now in `main`.

It typically takes about an hour before fixes are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by bnoctis** [comment]
Tried the [actions build](https://github.com/wez/wezterm/actions/runs/2958015160); repeatedly opening and closing panes in a SSH session still results in this error, around 50-70 opens I guess. My testing might be too fast.

```
04:50:12.526  ERROR  env_bootstrap    > panic at mux/src/lib.rs:216:41 - !?
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: env_bootstrap::register_panic_hook::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: mux::read_from_pane_pty
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: std::sys::unix::thread::Thread::new::thread_start
  13: __pthread_deallocate

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Socketpair(Os { code: 24, kind: Uncategorized, message: "Too many open files" })', mux/src/lib.rs:216:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
04:50:12.633  WARN   wezterm_ssh::pty > ssh: setenv COLORTERM=truecolor failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.636  WARN   wezterm_ssh::pty > ssh: setenv TERM=xterm-256color failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.639  WARN   wezterm_ssh::pty > ssh: setenv TERM_PROGRAM=WezTerm failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.641  WARN   wezterm_ssh::pty > ssh: setenv TERM_PROGRAM_VERSION=20220807-113146-c2fee766 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.644  WARN   wezterm_ssh::pty > ssh: setenv WEZTERM_REMOTE_PANE=45 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.648  ERROR  wezterm_gui::termwindow::spawn > Failed to spawn: split_pane: failed to create a socketpair: Too many open files (os error 24)
04:50:12.742  WARN   wezterm_ssh::pty               > ssh: setenv TERM_PROGRAM_VERSION=20220807-113146-c2fee766 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.746  WARN   wezterm_ssh::pty               > ssh: setenv WEZTERM_REMOTE_PANE=46 failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.748  WARN   wezterm_ssh::pty               > ssh: setenv TERM_PROGRAM=WezTerm failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.751  WARN   wezterm_ssh::pty               > ssh: setenv TERM=xterm-256color failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.753  WARN   wezterm_ssh::pty               > ssh: setenv COLORTERM=truecolor failed: RequestDenied: Channel request env failed. Check the AcceptEnv setting on the ssh server side.
04:50:12.756  ERROR  wezterm_gui::termwindow::spawn > Failed to spawn: split_pane: failed to create a socketpair: Too many open files (os error 24)
```

**Comment by wez** [comment]
I don't think you're actually running the new build because the line number in your latest error message is the same as your OP and that line doesn't panic any more.
Can you verify the version by pressing CTRl-SHIFT-L and checking the git hash in the version string?

**Comment by bnoctis** [comment]
It's 20220830-094332-97eaa581, and does have this problem. Just reconfirmed. Maybe I should enable some debug flag and upload a log?

**Comment by wez** [comment]
Perhaps you didn't upload the right log?

Line 216 is a blank line in that revision:
https://github.com/wez/wezterm/blob/main/mux/src/lib.rs#L216

**Comment by bnoctis** [comment]
Right, forgot that the MacPorts install linking.

But now it just got SIGKILL'd. I'll try a local build then.

**Comment by wez** [comment]
I can't reproduce this issue with `main` on either Linux or macOS

**Comment by bnoctis** [comment]
Anyway, I have changed the way to use it, mostly reusing windows and panes. Closing this for now.

**Comment by gmile** [comment]
Seeing a similar issue on `wezterm 20221119-145034-49b9839f`. The difference between mine and the originally reported one in the error type:

* mine:

    ```
    Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }
    ```

* og 

    ```
    Socketpair(Os { code: 24, kind: Uncategorized, message: "Too many open files" }
    ```

Full backtrace:
```
RUST_BACKTRACE=full wezterm
10:34:22.982  ERROR  env_bootstrap > panic at config/src/lib.rs:441:59 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  16: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:392:3
  17: <unknown>

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 24, kind: Uncategorized, message: "Too many open files" }), paths: [] }', config/src/lib.rs:441:59
stack backtrace:
   0:     0x561cb648c090 - <unknown>
   1:     0x561cb64b546e - <unknown>
   2:     0x561cb6484045 - <unknown>
   3:     0x561cb648dcd3 - <unknown>
   4:     0x561cb648d9bf - <unknown>
   5:     0x561cb59da7d7 - <unknown>
   6:     0x561cb648e41d - <unknown>
   7:     0x561cb648e277 - <unknown>
   8:     0x561cb648c53c - <unknown>
   9:     0x561cb648df92 - <unknown>
  10:     0x561cb59432e3 - <unknown>
  11:     0x561cb5943433 - <unknown>
  12:     0x561cb5fc5cc8 - <unknown>
  13:     0x561cb5fc3cb6 - <unknown>
  14:     0x561cb598a5a9 - <unknown>
  15:     0x561cb5988109 - <unknown>
  16:     0x561cb596ef03 - <unknown>
  17:     0x561cb59a99f9 - <unknown>
  18:     0x561cb647c74f - <unknown>
  19:     0x561cb599e798 - <unknown>
  20:     0x7faa05d4bd90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  21:     0x7faa05d4be40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  22:     0x561cb594361e - <unknown>
  23:                0x0 - <unknown>
```

**Comment by wez** [comment]
@gmile please open a separate issue so that I can track and respond to you effectively

**Comment by gmile** [comment]
@wez makes sense, created a separate issue at https://github.com/wez/wezterm/issues/3027
