### ISSUE TITLE
Crash on startup: `ERROR  env_bootstrap > panic at mux/src/tab.rs:497:23 - attempt to divide by zero`

### ISSUE THREAD

**Issue by wimstefan** [wez/wezterm#2593]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

-- awesome v4.3-1539-gb16f6286-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.1.0-beta3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no

-- picom
  dccsillag fork vgit-e0758

### WezTerm version

20221004-190909-eefd57b8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

This is the error I get with `RUST_BACKTRACE=full wezterm start`
```rust
ERROR  env_bootstrap > panic at mux/src/tab.rs:497:23 - attempt to divide by zero
```

For the full error log please see below.

### To Reproduce

Start wezterm with `RUST_BACKTRACE=full wezterm start`

### Configuration

Not sure what the relevant part is but I've included the whole config below ...
<details>
<summary>My wezterm config</summary>

```lua
local wezterm = require('wezterm')
local act = wezterm.action
-- local mux = wezterm.mux
local hostname = wezterm.hostname()
local my_font = 'custom'
-- local selected_scheme = 'wilmersdorf' -- dark
-- local selected_scheme = 'iceberg-light' -- light
local selected_scheme = 'seoulbones_light'

local function basename(s)
  return string.gsub(s, "(.*[/\\])(.*)", "%2")
end

-- Colour configuration
-- see https://github.com/wez/wezterm/issues/2376#issuecomment-1208816450
local scheme = wezterm.get_builtin_color_schemes()[selected_scheme]
local C_FG = scheme.foreground
local C_BG = scheme.background
---@diagnostic disable-next-line: unused-local
local C_BLACK = scheme.ansi[1]
---@diagnostic disable-next-line: unused-local
local C_RED = scheme.ansi[2]
---@diagnostic disable-next-line: unused-local
local C_GREEN = scheme.ansi[3]
---@diagnostic disable-next-line: unused-local
local C_YELLOW = scheme.ansi[4]
---@diagnostic disable-next-line: unused-local
local C_BLUE = scheme.ansi[5]
---@diagnostic disable-next-line: unused-local
local C_MAGENTA = scheme.ansi[6]
---@diagnostic disable-next-line: unused-local
local C_CYAN = scheme.ansi[7]
---@diagnostic disable-next-line: unused-local
local C_WHITE = scheme.ansi[8]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_BLACK = scheme.ansi[9]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_RED = scheme.ansi[10]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_GREEN = scheme.ansi[11]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_YELLOW = scheme.ansi[12]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_BLUE = scheme.ansi[13]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_MAGENTA = scheme.ansi[14]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_CYAN = scheme.ansi[15]
---@diagnostic disable-next-line: unused-local
local C_BRIGHT_WHITE = scheme.ansi[16]
local fg = wezterm.color.parse(scheme.foreground)
local bg = wezterm.color.parse(scheme.background)
---@diagnostic disable-next-line: unused-local
local h, s, l, a = fg:hsla()
if l > 0.5 then
  C_FG = fg:complement_ryb():lighten(0.4)
  C_BG = bg:darken(0.2)
else
  C_FG = fg:complement_ryb():darken(0.8)
  C_BG = bg:lighten(0.6)
end
scheme.foreground = C_FG
scheme.background = C_BG
scheme.tab_bar = {
  background = C_BG,
  active_tab = {
    bg_color = C_BG,
    fg_color = C_FG,
    intensity = 'Bold'
  },
  inactive_tab = {
    bg_color = C_BG,
    fg_color = C_FG,
    intensity = 'Half'
  },
  inactive_tab_hover = {
    bg_color = C_BG,
    fg_color = C_FG,
    intensity = 'Half'
  },
  new_tab = {
    bg_color = C_BG,
    fg_color = C_FG,
  },
  new_tab_hover = {
    bg_color = C_BG,
    fg_color = C_FG,
    italic = true
  }
}
scheme.scrollbar_thumb = C_BLUE
scheme.split = C_BLUE
scheme.compose_cursor = C_BRIGHT_GREEN
scheme.visual_bell = C_BRIGHT_RED

-- Font configuration
local function font_fallback(name)
  local names = { name, 'nonicons', 'JoyPixels', 'OpenMoji',
    { family = 'Iosevka Artesanal', weight = 'Book', scale = 1.1 } }
  return wezterm.font_with_fallback(names)
end

local function font_set(name)
  local font
  if string.match(name, 'custom') then
    font = font_fallback({ family = 'JetBrains Mono' })
  elseif string.match(name, 'fantasque') then
    font = font_fallback({ family = 'Fantasque Sans Mono', weight = 'Regular' })
  elseif string.match(name, 'iosevka') then
    font = font_fallback({ family = 'Iosevka Artesanal', harfbuzz_features = { 'calt=1', 'ccmp=1', 'dlig=1', 'onum=1' } })
  elseif string.match(name, 'operator') then
    font = font_fallback({ family = 'Operator Mono', weight = 'Book' })
  elseif string.match(name, 'plex') then
    font = font_fallback({ family = 'IBM Plex Mono Text', harfbuzz_features = { 'zero' } })
  elseif string.match(name, 'recursive') then
    font = font_fallback({ family = 'Rec Mono Casual', weight = 'Regular' })
  end
  return font
end

local function font_rules(name)
  local rules = {}
  if string.match(name, 'custom') then
    rules = nil
  elseif string.match(name, 'fantasque') then
    rules = {
      {
        intensity = 'Bold',
        italic = false,
        font = font_fallback({ family = 'Fantasque Sans Mono', weight = 'Bold' })
      },
      {
        intensity = 'Normal',
        italic = true,
        font = font_fallback({ family = 'Fantasque Sans Mono', weight = 'Regular', style = 'Italic' })
      },
      {
        intensity = 'Bold',
        italic = true,
        font = font_fallback({ family = 'Fantasque Sans Mono', weight = 'Bold', style = 'Italic' })
      },
    }
  elseif string.match(name, 'iosevka') then
    rules = {
      {
        intensity = 'Bold',
        italic = false,
        font = font_fallback({ family = 'Iosevka Artesanal', weight = 'Bold',
          harfbuzz_features = { 'calt=1', 'ccmp=1', 'dlig=1', 'onum=1' } }),
      },
      {
        intensity = 'Normal',
        italic = true,
        font = font_fallback({ family = 'Iosevka Artesanal', weight = 'Book', style = 'Italic' })
      },
      {
        intensity = 'Bold',
        italic = true,
        font = font_fallback({ family = 'Iosevka Artesanal', weight = 'Bold', style = 'Italic' })
      },
    }
  elseif string.match(name, 'operator') then
    rules = {
      {
        intensity = 'Bold',
        italic = false,
        font = font_fallback({ family = 'Operator Mono', weight = 'Medium' })
      },
      {
        intensity = 'Normal',
        italic = true,
        font = font_fallback({ family = 'Operator Mono', weight = 'Book', style = 'Italic' })
      },
      {
        intensity = 'Bold',
        italic = true,
        font = font_fallback({ family = 'Operator Mono', weight = 'Medium', style = 'Italic' })
      },
    }
  elseif string.match(name, 'plex') then
    rules = {
      {
        intensity = 'Bold',
        italic = false,
        font = font_fallback({ family = 'IBM Plex Mono SmBld', harfbuzz_features = { 'zero' } })
      },
      {
        intensity = 'Normal',
        italic = true,
        font = font_fallback({ family = 'IBM Plex Mono Text', style = 'Italic', harfbuzz_features = { 'zero' } })
      },
      {
        intensity = 'Bold',
        italic = true,
        font = font_fallback({ family = 'IBM Plex Mono SmBld', style = 'Italic', harfbuzz_features = { 'zero' } })
      },
    }
  elseif string.match(name, 'recursive') then
    rules = {
      {
        intensity = 'Bold',
        italic = false,
        font = font_fallback({ family = 'Rec Mono Casual', weight = 'Bold' })
      },
      {
        intensity = 'Normal',
        italic = true,
        font = font_fallback({ family = 'Rec Mono Casual', weight = 'Regular', style = 'Italic' })
      },
      {
        intensity = 'Bold',
        italic = true,
        font = font_fallback({ family = 'Rec Mono Casual', weight = 'Bold', style = 'Italic' })
      },
    }
  end
  return rules
end

local function font_size(name)
  local size
  if hostname == 'swimmer' then
    if string.match(name, 'custom') then
      size = 10.0
    elseif string.match(name, 'fantasque') then
      size = 11.4
    elseif string.match(name, 'iosevka') then
      size = 11.0
    elseif string.match(name, 'operator') then
      size = 11.0
    elseif string.match(name, 'plex') then
      size = 10.6
    elseif string.match(name, 'recursive') then
      size = 9.9
    end
  elseif hostname == 'tj' then
    if string.match(name, 'custom') then
      size = 10.0
    elseif string.match(name, 'fantasque') then
      size = 11.0
    elseif string.match(name, 'iosevka') then
      size = 10.4
    elseif string.match(name, 'operator') then
      size = 11.0
    elseif string.match(name, 'plex') then
      size = 10.4
    elseif string.match(name, 'recursive') then
      size = 9.4
    end
  end
  return size
end

local function set_geometry(x)
  local value = 0
  if x == 'cols' then
    value = 160
  elseif x == 'rows' then
    if hostname == 'swimmer' then
      if my_font == 'recursive' then
        value = 62
      elseif my_font == 'iosevka' then
        value = 64
      end
    elseif hostname == 'tj' then
      if my_font == 'recursive' then
        value = 51
      elseif my_font == 'iosevka' then
        value = 50
      end
    end
  end
  return value
end

---@diagnostic disable-next-line: unused-local
local function update_ssh_status(window, pane)
  local text = pane:get_domain_name()
  if text == "local" then
    text = hostname
  end
  return text
end

wezterm.on('format-tab-title', function(tab)
  local tab_prefix = tab.tab_index == 0 and "  " or " "
  local tab_index = tab.tab_index
  local pane = tab.active_pane
  -- local tab_title = tab_index .. ' ' .. tab.active_pane.title
  local tab_title = tab_index .. ' ' .. basename(pane.foreground_process_name)
  if tab.is_active then
    return {
      { Text = tab_prefix },
      { Text = pane.is_zoomed and '⸢' .. tab_title .. '  ' .. '⸥' or '⸢' .. tab_title .. '⸥' }
    }
  end
  return {
    { Text = tab_prefix },
    { Text = pane.is_zoomed and tab_title .. '  ' or tab_title }
  }
end)

wezterm.on('update-right-status', function(window, pane)
  local host = update_ssh_status(window, pane)
  local host_name = wezterm.hostname()
  local date = wezterm.strftime('[%H:%M] %a %b %d %Y  ')
  local bat = ''
  for _, b in ipairs(wezterm.battery_info()) do
    bat = string.format('[BAT] %.0f%% ', b.state_of_charge * 100)
  end
  window:set_right_status(wezterm.format({
    { Attribute = { Intensity = 'Bold' } },
    { Foreground = { AnsiColor = 'Green' } },
    { Text = '• ' .. host .. ': ' .. host_name .. ' •' .. ' ' },
    { Foreground = { AnsiColor = 'Yellow' } },
    { Text = bat },
    { Foreground = 'Default' },
    { Text = date },
  }))
end)

-- wezterm.on('gui-startup', function(cmd)
--     local tab, top_pane, window = mux.spawn_window(cmd or {})
--     local bottom_pane = top_pane:split { direction = 'Bottom' }
--     top_pane:split { direction = 'Right'}
--     bottom_pane:split { direction = 'Right'}
-- end)

return {
  color_schemes = {
    [selected_scheme] = scheme
  },
  color_scheme = selected_scheme,
  force_reverse_video_cursor = true,

  -- Fonts
  font = font_set(my_font),
  font_rules = font_rules(my_font),
  font_size = font_size(my_font),
  char_select_font_size = font_size(my_font),
  freetype_load_target = 'Light',
  allow_square_glyphs_to_overflow_width = 'WhenFollowedBySpace',
  custom_block_glyphs = true,
  warn_about_missing_glyphs = false,
  underline_position = '-1.4pt',
  underline_thickness = '200%',
  unicode_version = 14,

  -- Behaviour
  term = 'wezterm',
  check_for_updates = false,
  adjust_window_size_when_changing_font_size = false,
  window_background_opacity = 0.7,
  window_padding = {
    left = '3cell',
    right = '3cell',
    top = '1cell',
    bottom = '1cell',
  },
  initial_cols = set_geometry('cols'),
  initial_rows = set_geometry('rows'),
  enable_kitty_graphics = true,
  enable_kitty_keyboard = true,
  selection_word_boundary = ' \t\n{}"\'`,;@│*',
  clean_exit_codes = { 127, 130, 255 },

  -- Tabs
  hide_tab_bar_if_only_one_tab = true,
  use_fancy_tab_bar = false,
  tab_bar_at_bottom = true,
  tab_max_width = 44,
  show_tab_index_in_tab_bar = true,

  -- Panes
  pane_focus_follows_mouse = true,
  swallow_mouse_click_on_pane_focus = true,
  swallow_mouse_click_on_window_focus = true,
  inactive_pane_hsb = {
    saturation = 0.7,
    brightness = 1.0,
  },

  -- Hyperlinks
  hyperlink_rules = {
    {
      regex = '\\b\\w+://(?:[\\w.-]+)\\.[a-z0-9]{2,15}\\S*\\b',
      format = '$0',
    },
  },

  -- Key bindings
  disable_default_key_bindings = true,
  use_ime = false,
  debug_key_events = false,
  leader = { key = 'q', mods = 'CTRL' },
  keys = {
    { key = '-', mods = 'CTRL', action = act.DecreaseFontSize },
    { key = '=', mods = 'CTRL', action = act.IncreaseFontSize },
    { key = '0', mods = 'CTRL', action = act.ResetFontSize },
    { key = 'c', mods = 'CTRL|SHIFT', action = act.CopyTo 'Clipboard' },
    { key = 'v', mods = 'CTRL|SHIFT', action = act.PasteFrom 'Clipboard' },
    { key = 'Z', mods = 'CTRL|SHIFT', action = act.CharSelect },
    { key = 'PageUp', mods = 'SHIFT', action = act.ScrollByPage(-1) },
    { key = 'PageDown', mods = 'SHIFT', action = act.ScrollByPage(1) },
    { key = 'd', mods = 'LEADER', action = act.ShowDebugOverlay },
    { key = 'l', mods = 'LEADER', action = act.ShowLauncher },
    { key = 'Space', mods = 'LEADER', action = act.QuickSelect },
    { key = 'f', mods = 'LEADER', action = act.Search{ CaseSensitiveString = '' } },
    { key = 'x', mods = 'LEADER', action = act.ActivateCopyMode },
    { key = 'e', mods = 'LEADER',
      action = act.QuickSelectArgs{
        label = 'open url',
        patterns = {
          'https?://\\S+'
        },
        action = wezterm.action_callback(function(window, pane)
          local url = window:get_selection_text_for_pane(pane)
          wezterm.log_info('opening: ' .. url)
          wezterm.open_with(url)
        end)
      }
    },
    { key = 't', mods = 'LEADER', action = act.SpawnTab 'CurrentPaneDomain' },
    { key = 'w', mods = 'LEADER', action = act.CloseCurrentPane{ confirm = true } },
    { key = 'w', mods = 'LEADER|SHIFT', action = act.CloseCurrentTab{ confirm = true } },
    { key = '|', mods = 'LEADER|SHIFT', action = act.SplitHorizontal{ domain = 'CurrentPaneDomain' } },
    { key = '-', mods = 'LEADER', action = act.SplitVertical{ domain = 'CurrentPaneDomain' } },
    { key = 'P', mods = 'LEADER', action = act.PaneSelect },
    { key = 'z', mods = 'LEADER', action = act.TogglePaneZoomState },
    { key = '0', mods = 'LEADER', action = act.ActivateTab(0) },
    { key = '1', mods = 'LEADER', action = act.ActivateTab(1) },
    { key = '2', mods = 'LEADER', action = act.ActivateTab(2) },
    { key = '3', mods = 'LEADER', action = act.ActivateTab(3) },
    { key = '4', mods = 'LEADER', action = act.ActivateTab(4) },
    { key = '5', mods = 'LEADER', action = act.ActivateTab(5) },
    { key = '6', mods = 'LEADER', action = act.ActivateTab(6) },
    { key = '7', mods = 'LEADER', action = act.ActivateTab(7) },
    { key = '8', mods = 'LEADER', action = act.ActivateTab(8) },
    { key = '9', mods = 'LEADER', action = act.ActivateTab(9) },
    { key = 'p', mods = 'LEADER', action = act.ActivateTabRelative(-1) },
    { key = 'n', mods = 'LEADER', action = act.ActivateTabRelative(1) },
    { key = 'o', mods = 'LEADER', action = act.ActivateLastTab },
    { key = 'LeftArrow', mods = 'LEADER', action = act.ActivatePaneDirection 'Left' },
    { key = 'RightArrow', mods = 'LEADER', action = act.ActivatePaneDirection 'Right' },
    { key = 'UpArrow', mods = 'LEADER', action = act.ActivatePaneDirection 'Up' },
    { key = 'DownArrow', mods = 'LEADER', action = act.ActivatePaneDirection 'Down' },
    { key = 'LeftArrow', mods = 'LEADER|SHIFT', action = act.AdjustPaneSize{ 'Left', 4 } },
    { key = 'RightArrow', mods = 'LEADER|SHIFT', action = act.AdjustPaneSize{ 'Right', 4 } },
    { key = 'UpArrow', mods = 'LEADER|SHIFT', action = act.AdjustPaneSize{ 'Up', 4 } },
    { key = 'DownArrow', mods = 'LEADER|SHIFT', action = act.AdjustPaneSize{ 'Down', 4 } },
  },
}
```
</details>

### Expected Behavior

Starting up a working terminal :)

### Logs

```rust
 10:15:00.502  ERROR  env_bootstrap > panic at mux/src/tab.rs:497:23 - attempt to divide by zero
   0: env_bootstrap::register_panic_hook::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:586:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   6: core::panicking::panic
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
   7: mux::tab::Tab::prune_dead_panes
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: mux::window::Window::prune_dead_tabs
  10: mux::Mux::prune_dead_windows
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  12: async_task::raw::RawTask<F,T,S>::run
  13: window::spawn::SpawnQueue::run
  14: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
  15: wezterm_gui::main
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
  17: std::rt::lang_start::{{closure}}
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
      std::panicking::try::do_call
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
      std::panicking::try
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
      std::panic::catch_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
      std::rt::lang_start_internal
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  19: main
  20: <unknown>
  21: __libc_start_main
  22: _start

thread 'main' panicked at 'attempt to divide by zero', mux/src/tab.rs:497:23
stack backtrace:
   0:     0x560ef59286ed - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x560ef59286ed - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560ef59286ed - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x560ef59286ed - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x560ef595314c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x560ef5920241 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x560ef592a445 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x560ef592a445 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x560ef592a445 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x560ef592a161 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x560ef4611bb8 - env_bootstrap::register_panic_hook::{{closure}}::hb1ff294b365689f5
  11:     0x560ef592aa8a - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:702:17
  12:     0x560ef592a889 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:586:13
  13:     0x560ef5928be4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x560ef592a5f9 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  15:     0x560ef42724f3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  16:     0x560ef42723bd - core::panicking::panic::hb3ad04c589a0e3c8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:48:5
  17:     0x560ef4a0449b - mux::tab::Tab::prune_dead_panes::h781fded065f98f92
  18:     0x560ef4afff24 - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::hff7a11b9e1c1e67e
  19:     0x560ef4ac984b - mux::window::Window::prune_dead_tabs::hc1b949c614c2bc38
  20:     0x560ef4a54416 - mux::Mux::prune_dead_windows::ha1efd65cfb784983
  21:     0x560ef4a7104c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0e1b21c85e7bd526
  22:     0x560ef4b0d8f4 - async_task::raw::RawTask<F,T,S>::run::hf4d705f3251050c9
  23:     0x560ef4cd0113 - window::spawn::SpawnQueue::run::h4eeae2a9705e408b
  24:     0x560ef4daef0d - <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop::h26e37df237feaa33
  25:     0x560ef44e69ce - wezterm_gui::main::hb7a7b2e104720590
  26:     0x560ef43a20b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha4a71a9a8c58a77c
  27:     0x560ef43d4219 - std::rt::lang_start::{{closure}}::h11c0130628cfbc45
  28:     0x560ef591807e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  29:     0x560ef591807e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  30:     0x560ef591807e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  31:     0x560ef591807e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  32:     0x560ef591807e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  33:     0x560ef591807e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  34:     0x560ef591807e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  35:     0x560ef591807e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  36:     0x560ef591807e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  37:     0x560ef44f19e2 - main
  38:     0x7f2e9e0b22ca - <unknown>
  39:     0x7f2e9e0b2385 - __libc_start_main
  40:     0x560ef4272cb1 - _start
  41:                0x0 - <unknown>
```

**Comment by wez** [comment]
The divide by zero is because the number of rows in the terminal is 0.
I'd suggest commenting out the `initial_rows`/`initial_cols` from your config to see if that prevents this?
Alternatively, if there is something else in your config (or environment) that might lead to the size being 0, I'd suggest checking that.

I could do something to prevent the panic for a divide by zero, by eg: just treating the result as 0, but the best case is that you end up with a weirdly sized window.  I'd like to understand more about how we end up with that 0 before trying to fix this particular panic.

**Comment by wimstefan** [comment]
Now that's interesting!

I have this function in my config
```lua
local function set_geometry(x)
  local value = 0
  if x == 'cols' then
    value = 160
  elseif x == 'rows' then
    if hostname == 'swimmer' then
      if my_font == 'recursive' then
        value = 62
      elseif my_font == 'iosevka' then
        value = 64
      end
    elseif hostname == 'tj' then
      if my_font == 'recursive' then
        value = 51
      elseif my_font == 'iosevka' then
        value = 50
      end
    end
  end
  return value
end
```
that I call with
```lua
  initial_cols = set_geometry('cols'),
  initial_rows = set_geometry('rows'),
```
and that used to work all the time but throws an error now ...
I guess I have to re-work that function than ;)

Thanks for putting me on the right track!  🙏

PS: Having to use kitty again let's me appreciate WezTerm even more :D

**Comment by wimstefan** [comment]
OK - I declare myself officially a **stupid fool**!
I've changed the value of `my_font` and didn't catch that in the function. No wonder it throws an error ;)
How embarassing :(
Sorry for wasting your time.
