### ISSUE TITLE
Error: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by KaziSadmanAhmed** [wez/wezterm#2596]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

WM: qtile 0.22.1

### WezTerm version

wezterm 20221004-190909-eefd57b8

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Installed the `wezterm-git` package from AUR. Crashing when trying to start it using the `wezterm` command.

### Configuration

no config

### Logs

```
>>> wezterm
02:27:22.516  ERROR  env_bootstrap > panic at /home/sadman/.local/share/cargo/git/checkouts/rust-xcb-41cc7e93ef1d12da/a85a4cf/src/event.rs:255:83 - called `Option::unwrap()` on a `None` value
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: __libc_start_main
  18: <unknown>

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/sadman/.local/share/cargo/git/checkouts/rust-xcb-41cc7e93ef1d12da/a85a4cf/src/event.rs:255:83
stack backtrace:
   0:     0x560f03839d7d - <unknown>
   1:     0x560f0386488c - <unknown>
   2:     0x560f03831741 - <unknown>
   3:     0x560f0383bad5 - <unknown>
   4:     0x560f0383b7f1 - <unknown>
   5:     0x560f02370d78 - <unknown>
   6:     0x560f0383c11a - <unknown>
   7:     0x560f0383bf19 - <unknown>
   8:     0x560f0383a274 - <unknown>
   9:     0x560f0383bc89 - <unknown>
  10:     0x560f01fd3533 - <unknown>
  11:     0x560f01fd33fd - <unknown>
  12:     0x560f02e0973f - <unknown>
  13:     0x560f02e08cda - <unknown>
  14:     0x560f02e08e51 - <unknown>
  15:     0x560f02cfecd1 - <unknown>
  16:     0x560f022480c5 - <unknown>
  17:     0x560f02095453 - <unknown>
  18:     0x560f021031f9 - <unknown>
  19:     0x560f0382955e - <unknown>
  20:     0x560f02252d22 - <unknown>
  21:     0x7ff9a5272290 - <unknown>
  22:     0x7ff9a527234a - __libc_start_main
  23:     0x560f01fd3cf5 - <unknown>
  24:                0x0 - <unknown>
```

**Comment by wez** [comment]
Duplicate of https://github.com/wez/wezterm/issues/2559
