### ISSUE TITLE
Launcher menu fuzzy completion hangs when confirming a blank candidate

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2629]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 i3

### WezTerm version

wezterm 20221011-202755-7ba9c00e

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

The fuzzy finder can trigger a panic under the specific condition that you try selecting a candidate when there are no candidates.

### To Reproduce

If you open a fuzzy launcher menu, and filter it down to 0 items in the list, then press enter, wezterm almost completely freezes. The only thing I can do is right click on the launcher tab, which then crashes with the following panic:

```
02:23:39.206  ERROR  env_bootstrap           > panic at wezterm-gui/src/overlay/launcher.rs:415:26 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', wezterm-gui/src/overlay/launcher.rs:415:26
stack backtrace:
   0:     0x5563fad1762d - <unknown>
   1:     0x5563fad4213c - <unknown>
   2:     0x5563fad0eff1 - <unknown>
   3:     0x5563fad19385 - <unknown>
   4:     0x5563fad190a1 - <unknown>
   5:     0x5563f9825198 - <unknown>
   6:     0x5563fad199ca - <unknown>
   7:     0x5563fad19807 - <unknown>
   8:     0x5563fad17b24 - <unknown>
   9:     0x5563fad19539 - <unknown>
  10:     0x5563f94823f3 - <unknown>
  11:     0x5563f9482332 - <unknown>
  12:     0x5563f9679546 - <unknown>
  13:     0x5563f967b317 - <unknown>
  14:     0x5563f95ad12c - <unknown>
  15:     0x5563f953efd7 - <unknown>
  16:     0x5563fad1f763 - <unknown>
  17:     0x7f797abec8fd - <unknown>
  18:     0x7f797ac6ea60 - <unknown>
  19:                0x0 - <unknown>
```

Built with `--release` and the debug=1 switch under that section in Cargo.toml.

gdb backtrace:

```
mfiano@workstation ~$ RUST_BACKTRACE=full gdb wezterm
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from wezterm...
(No debugging symbols found in wezterm)
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/bin/wezterm.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /usr/bin/wezterm
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff7be56c0 (LWP 912353)]
[Thread 0x7ffff7be56c0 (LWP 912353) exited]
process 912350 is executing new program: /usr/bin/wezterm-gui
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /usr/bin/wezterm-gui.
Use `info auto-load python-scripts [REGEXP]' to list them.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff75bb6c0 (LWP 912354)]
[New Thread 0x7ffff73056c0 (LWP 912355)]
[New Thread 0x7ffff71046c0 (LWP 912356)]
02:27:53.624  ERROR  wezterm_gui::termwindow > new_window has no tabs... yet?
[New Thread 0x7ffff4c9c6c0 (LWP 912357)]
[New Thread 0x7ffff4a9b6c0 (LWP 912358)]
[New Thread 0x7ffff489a6c0 (LWP 912359)]
[New Thread 0x7ffff46996c0 (LWP 912360)]
[New Thread 0x7ffff44986c0 (LWP 912361)]
[New Thread 0x7ffff42976c0 (LWP 912362)]
[New Thread 0x7fffd7fff6c0 (LWP 912363)]
[New Thread 0x7fffd7dfe6c0 (LWP 912364)]
[New Thread 0x7fffd7bfd6c0 (LWP 912365)]
[New Thread 0x7fffd79fc6c0 (LWP 912366)]
[New Thread 0x7fffd77fb6c0 (LWP 912367)]
[New Thread 0x7fffd75fa6c0 (LWP 912368)]
[New Thread 0x7fffd73f96c0 (LWP 912369)]
[New Thread 0x7fffd71f86c0 (LWP 912370)]
[New Thread 0x7fffd6ff76c0 (LWP 912371)]
[New Thread 0x7fffd6df66c0 (LWP 912372)]
[New Thread 0x7fffd6bf56c0 (LWP 912373)]
[New Thread 0x7fffd69f46c0 (LWP 912374)]
[New Thread 0x7fffd67f36c0 (LWP 912375)]
[New Thread 0x7fffd65f26c0 (LWP 912376)]
[New Thread 0x7fffd63f16c0 (LWP 912377)]
[New Thread 0x7fffd61f06c0 (LWP 912378)]
[New Thread 0x7fffd5fef6c0 (LWP 912379)]
[New Thread 0x7fffd5dee6c0 (LWP 912380)]
[New Thread 0x7fffd5bed6c0 (LWP 912381)]
[Thread 0x7fffd5bed6c0 (LWP 912381) exited]
[New Thread 0x7fffd5bed6c0 (LWP 912382)]
[New Thread 0x7fffd59ec6c0 (LWP 912383)]
[New Thread 0x7fffd56ea6c0 (LWP 912384)]
[New Thread 0x7fffd44ee6c0 (LWP 912385)]
[New Thread 0x7fff793ff6c0 (LWP 912386)]
[New Thread 0x7fff791fe6c0 (LWP 912387)]
[New Thread 0x7fff78ffd6c0 (LWP 912388)]
[Thread 0x7fff78ffd6c0 (LWP 912388) exited]
[Thread 0x7fff791fe6c0 (LWP 912387) exited]
02:27:54.073  WARN   wezterm_client::client  > While connecting to Socket("/run/user/1000/wezterm/sock"): connecting to /run/user/1000/wezterm/sock.  Will try spawning the server.
02:27:54.074  WARN   wezterm_client::client  > Running: "/usr/bin/wezterm-mux-server" "--daemonize"
[Detaching after fork from child process 912389]
[New Thread 0x7fff791fe6c0 (LWP 912390)]
[Thread 0x7fff791fe6c0 (LWP 912390) exited]
[New Thread 0x7fff791fe6c0 (LWP 912451)]
[Thread 0x7ffff71046c0 (LWP 912356) exited]
[Thread 0x7fffd44ee6c0 (LWP 912385) exited]
[Thread 0x7fffd56ea6c0 (LWP 912384) exited]
[Thread 0x7fffd59ec6c0 (LWP 912383) exited]
[Thread 0x7fffd5bed6c0 (LWP 912382) exited]
[New Thread 0x7fffd5bed6c0 (LWP 912502)]
[New Thread 0x7fffd56ea6c0 (LWP 912503)]
[New Thread 0x7fffd44ee6c0 (LWP 912504)]
[New Thread 0x7fffd59ec6c0 (LWP 912505)]
02:27:59.502  ERROR  env_bootstrap           > panic at wezterm-gui/src/overlay/launcher.rs:415:26 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>

thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', wezterm-gui/src/overlay/launcher.rs:415:26
stack backtrace:
   0:     0x55555744162d - <unknown>
   1:     0x55555746c13c - <unknown>
   2:     0x555557438ff1 - <unknown>
   3:     0x555557443385 - <unknown>
   4:     0x5555574430a1 - <unknown>
   5:     0x555555f4f198 - <unknown>
   6:     0x5555574439ca - <unknown>
   7:     0x555557443807 - <unknown>
   8:     0x555557441b24 - <unknown>
   9:     0x555557443539 - <unknown>
  10:     0x555555bac3f3 - <unknown>
  11:     0x555555bac332 - <unknown>
  12:     0x555555da3546 - <unknown>
  13:     0x555555da5317 - <unknown>
  14:     0x555555cd712c - <unknown>
  15:     0x555555c68fd7 - <unknown>
  16:     0x555557449763 - <unknown>
  17:     0x7ffff7c0a8fd - <unknown>
  18:     0x7ffff7c8ca60 - <unknown>
  19:                0x0 - <unknown>
[Thread 0x7fffd59ec6c0 (LWP 912505) exited]
[Thread 0x7fffd44ee6c0 (LWP 912504) exited]
[Thread 0x7fffd56ea6c0 (LWP 912503) exited]

Thread 1 "wezterm-gui" received signal SIGINT, Interrupt.
0x00007ffff7c8c096 in epoll_wait () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7c8c096 in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000555557090ede in ?? ()
#2  0x00005555568f6d3a in ?? ()
#3  0x0000555555e5521b in ?? ()
#4  0x0000555555cd6733 in ?? ()
#5  0x0000555555d07f79 in ?? ()
#6  0x0000555557430e0e in ?? ()
#7  0x0000555555e5d488 in ?? ()
#8  0x00007ffff7ba7290 in ?? () from /usr/lib/libc.so.6
#9  0x00007ffff7ba734a in __libc_start_main () from /usr/lib/libc.so.6
#10 0x0000555555bacbb5 in ?? ()
(gdb) exit
```

### Configuration

This occurs without any user configuration.

### Expected Behavior

To not panic :)

### Logs

See description.

**Comment by wez** [comment]
This should be implemented now in `main`.

It typically takes about an hour before commits are available as nightly builds for all platforms.  Linux builds are the fastest to build and are often available within about 20 minutes.  Windows and macOS builds take a bit longer.

Please take a few moments to try out the fix and let me know how that works out. You can find the nightly downloads for your system in the [wezterm installation docs](https://wezfurlong.org/wezterm/installation.html).

If you prefer to use packages provided by your distribution or package manager of choice and don't want to replace that with a nightly download, keep in mind that you can download portable packages (eg: a `.dmg` file on macOS, a `.zip` file on Windows and an `.AppImage` file on Linux) that can be run without permanently installing or replacing an existing package, and can then simply be deleted once you no longer need them. 

If you are eager and can [build from source](https://wezfurlong.org/wezterm/install/source.html) then you may be able to try this out more quickly.

**Comment by mfiano** [comment]
Confirmed fix. Thanks!
