### ISSUE TITLE
Panic when setting a workspace

### ISSUE THREAD

**Issue by mfiano** [wez/wezterm#2638]
### What Operating System(s) are you seeing this problem on?

Linux X11

### Which Wayland compositor or X11 Window manager(s) are you using?

X11 i3

### WezTerm version

wezterm 20221015-164502-7b904f05

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

When using `set_workspace()` on a mux window passing it any string, and for any mux window, I always get a runtime crash.

### To Reproduce

Call `mux_window:set_workspace("something")` from somewhere within a `gui-startup` hook. It panics. This occurs with an otherwise vanilla configuration, even.

### Configuration

```lua
local wezterm = require 'wezterm'

wezterm.on("gui-startup", function()
  local _, _, window = wezterm.mux.spawn_window {}
  window:set_workspace("foo")
end)

return {
  default_domain = "main",
  unix_domains = { { name = "main" } }
}
```

### Expected Behavior

To not crash.

### Logs

```
mfiano@workstation ~$ killall wezterm-mux-server && wezterm
19:15:14.065  WARN   wezterm_client::client > While connecting to Socket("/run/user/1000/wezterm/sock"): connecting to /run/user/1000/wezterm/sock.  Will try spawning the server.
19:15:14.065  WARN   wezterm_client::client > Running: "/usr/bin/wezterm-mux-server" "--daemonize"
19:15:14.423  ERROR  env_bootstrap          > panic at mux/src/lib.rs:785:26 - !?
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: __libc_start_main
  37: <unknown>

thread 'main' panicked at 'already mutably borrowed: BorrowError', mux/src/lib.rs:785:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wez** [comment]
Here's the relevant portion of the panic, with debug info:

```
06:57:31.328  ERROR  env_bootstrap          > panic at mux/src/lib.rs:785:26 - !?
   0: env_bootstrap::register_panic_hook::{{closure}}
             at env-bootstrap/src/lib.rs:144:18
   1: std::panicking::rust_panic_with_hook
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   6: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   7: core::result::Result<T,E>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
   8: core::cell::RefCell<T>::borrow
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/cell.rs:863:9
   9: mux::Mux::get_window
             at mux/src/lib.rs:785:13
  10: wezterm_client::domain::mux_notify_client_domain
             at wezterm-client/src/domain.rs:284:42
  11: wezterm_client::domain::ClientDomain::new::{{closure}}
             at wezterm-client/src/domain.rs:310:37
  12: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/alloc/src/boxed.rs:1965:9
  13: mux::Mux::notify::{{closure}}
             at mux/src/lib.rs:564:40
  14: hashbrown::map::HashMap<K,V,S,A>::retain
             at /cargo/registry/src/github.com-1ecc6299db9ec823/hashbrown-0.12.3/src/map.rs:834:21
  15: std::collections::hash::map::HashMap<K,V,S>::retain
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/collections/hash/map.rs:689:9
  16: mux::Mux::notify
             at mux/src/lib.rs:564:9
  17: mux::window::Window::set_workspace
             at mux/src/window.rs:51:13
```

**Comment by mfiano** [comment]
If you change `"gui-startup"` to `"mux-startup"`, it works as expected.

**Comment by mfiano** [comment]
Fix confirmed. Thank you.
