### ISSUE TITLE
wezterm crashes on split resize by mouse

### ISSUE THREAD

**Issue by mborejdo** [wez/wezterm#276]
## Describe the bug

I have one vertical split (two panes) and wanted to try the split-drag-by-mouse-feature (which I usually would not use, though). Dragging it like crazy left/right, crashes wezterm. 

```
 2020-09-25T07:51:06.994Z ERROR wezterm::frontend::gui::termwindow > SplitHorizontal SpawnCommand { label: None, args: None, cwd: None, set_environment_variables: {}, domain: CurrentPaneDomain }
 2020-09-25T07:51:06.995Z ERROR wezterm::frontend::gui::termwindow > doing split_pane
 2020-09-25T07:51:10.182Z ERROR wezterm::localtab                  > Pane id 0 is_dead
 2020-09-25T07:51:10.210Z ERROR wezterm::mux                       > read_pty EOF: pane_id 0
```
## Environment (please complete the following information):

 - OS: Windows 10
 - Version: wezterm 20200909-002054-4c9af461-21-g7b855fb

## To Reproduce
start wezterm on Windows 10, split the terminalwindow, drag the thin line like crazy

**Comment by wez** [comment]
I haven't been able to reproduce this.  Did it print out anything more than the text above?
Could you try setting RUST_BACKTRACE=1 in the environment and try to reproduce it?

**Comment by mborejdo** [comment]
Unfortunately setting RUST_BACKTRACE=1 does not print additional Debug-Info. Is there anything else I can provide?
It seems that wezterm is not fully crashed, but only the visible window. I see running wezterm process still around, but the window disappeared.
a somehow related problem seems to occur when I close opened splits quickly. Sometimes all wezterm-windows disappear and my desktop (for example some other program) starts to "flicker" (will try to records this somehow).
If I kill all wezterm-processes, the "flickering" goes away.

**Comment by mborejdo** [comment]
![resize_panic](https://user-images.githubusercontent.com/52340/94401625-2cd1af80-016b-11eb-927b-f71fb2f69f2a.gif)
![resize1](https://user-images.githubusercontent.com/52340/94401632-2d6a4600-016b-11eb-849b-c36f3e3ee3e1.gif)
![resize_split](https://user-images.githubusercontent.com/52340/94401642-2fcca000-016b-11eb-91ce-d329b76f5f2d.gif)
![resize_split2](https://user-images.githubusercontent.com/52340/94401647-32c79080-016b-11eb-8024-4b755e16e85c.gif)
![resize_split3](https://user-images.githubusercontent.com/52340/94401665-38bd7180-016b-11eb-927c-7c87bb36a30b.gif)
```
 2020-09-28T07:10:18.932Z ERROR wezterm::frontend::gui::termwindow > SplitHorizontal SpawnCommand { label: None, args: None, cwd: None, set_environment_variables: {}, domain: CurrentPaneDomain }
 2020-09-28T07:10:18.933Z ERROR wezterm::frontend::gui::termwindow > doing split_pane
 2020-09-28T07:10:23.292Z ERROR wezterm::localtab                  > Pane id 1 is_dead
 2020-09-28T07:10:23.308Z ERROR wezterm::mux                       > read_pty EOF: pane_id 1
 2020-09-28T07:11:16.637Z ERROR wezterm::frontend::gui::termwindow > SplitHorizontal SpawnCommand { label: None, args: None, cwd: None, set_environment_variables: {}, domain: CurrentPaneDomain }
 2020-09-28T07:11:16.638Z ERROR wezterm::frontend::gui::termwindow > doing split_pane
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src\mux\tab.rs:407:63
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\core\src\option.rs:1221
   3: <wezterm::localtab::LocalPane as core::ops::drop::Drop>::drop
   4: wezterm::mux::tab::Tab::resize
   5: wezterm::frontend::gui::termwindow::TermWindow::spawn_command_impl
   6: wezterm::frontend::gui::termwindow::TermWindow::spawn_command_impl
   7: <alloc::vec::Vec<metrics_core::Label> as metrics_core::IntoLabels>::into_labels     8: window::os::windows::window::do_wnd_proc
   9: window::os::windows::window
```

**Comment by mborejdo** [comment]
cannot reproduce on latest master

**Comment by mborejdo** [comment]
oh, nvm, Unfortunately I still can reproduce the behaviour in the first gif. 
Other split-related problems do not apprear anymore.

**Comment by wez** [comment]
> oh, nvm, Unfortunately I still can reproduce the behaviour in the first gif.
> Other split-related problems do not apprear anymore.

Could you capture the updated stack trace for the issue that does occur on master?
I think that will look slightly different and that should help me run this down!

**Comment by mborejdo** [comment]
```
   2020-09-29T19:04:27.651Z ERROR wezterm::frontend::gui::termwindow > SplitHorizontal SpawnCommand { label: None, args: None, cwd: None, set_environment_variables: {}, domain: CurrentPaneDomain }
 2020-09-29T19:04:27.651Z ERROR wezterm::frontend::gui::termwindow > doing split_pane
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', src\mux\tab.rs:407:63
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/f44c6e4e288e4f49c5c257b2e2cb2ad5918f26a3\/library\core\src\option.rs:1221
   3: wezterm::scripting::run_child_process
   4: wezterm::mux::tab::Tab::resize
   5: wezterm::frontend::gui::termwindow::TermWindow::spawn_command_impl
   6: wezterm::frontend::gui::termwindow::TermWindow::spawn_command_impl
   7: <dyn wezterm::frontend::gui::termwindow::ShapeCacheKeyTrait as core::cmp::PartialEq>::eq
   8: window::os::windows::window::do_wnd_proc
   9: window::os::windows::window::do_wnd_proc
  10: CallWindowProcW
  11: CallWindowProcW
  12: <unknown>
  13: CallWindowProcW
  14: DispatchMessageW
  15: SendMessageTimeoutW
  16: KiUserCallbackDispatcher
  17: NtUserMessageCall
  18: SendMessageW
  19: GetWindowTextW
  20: IsIconic
  21: Ordinal132
  22: Ordinal132
  23: GetWindowTextW
  24: window::os::windows::window::do_wnd_proc
  25: CallWindowProcW
  26: CallWindowProcW
  27: <unknown>
  28: CallWindowProcW
  29: DispatchMessageW
  30: LookupIconIdFromDirectoryEx
  31: KiUserCallbackDispatcher
  32: NtUserMessageCall
  33: GetWindowTextW
  34: IsIconic
  35: OpenThemeData
  36: Ordinal96
  37: Ordinal132
  38: Ordinal132
  39: GetWindowTextW
  40: window::os::windows::window::do_wnd_proc
  41: CallWindowProcW
  42: CallWindowProcW
  43: <unknown>
  44: CallWindowProcW
  45: DispatchMessageW
  46: SendMessageTimeoutW
  47: KiUserCallbackDispatcher
  48: NtUserMessageCall
  49: GetWindowTextW
  50: IsIconic
  51: OpenThemeData
  52: Ordinal96
  53: Ordinal132
  54: Ordinal132
  55: GetWindowTextW
  56: window::os::windows::window::do_wnd_proc
  57: CallWindowProcW
  58: CallWindowProcW
  59: <unknown>
  60: CallWindowProcW
  61: DispatchMessageW
  62: <window::os::windows::connection::Connection as window::connection::ConnectionOps>::run_message_loop
  63: wezterm::terminate_with_error
  64: wezterm::terminate_with_error
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 2020-09-29T19:04:36.045Z ERROR window::os::windows::window        > caught Any
error: External command failed
  ┌─ shell:1:18
  │
1 │ RUST_BACKTRACE=1 wezterm
  │                  ^^^^^^^ command failed
  
```
