### ISSUE TITLE
Crash: window/os/wayland/connection.rs:191:35 called Option::unwrap on None

### ISSUE THREAD

**Issue by glyh** [wez/wezterm#3050]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Sway

### WezTerm version

wezterm 20230203-084517-5532ae24

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

wezterm won't start

### To Reproduce

start wezterm

### Configuration

no config

### Expected Behavior

starts

### Logs

```
11:12:00.680  ERROR  env_bootstrap > panic at window/src/os/wayland/connection.rs:191:35 - called `Option::unwrap()` on a `None` value
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_main
  19: <unknown>

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', window/src/os/wayland/connection.rs:191:35
stack backtrace:
   0:     0x56061100d550 - <unknown>
   1:     0x56061103750e - <unknown>
   2:     0x560611005375 - <unknown>
   3:     0x56061100d315 - <unknown>
   4:     0x56061100f0bf - <unknown>
   5:     0x56061100edfa - <unknown>
   6:     0x56060fabc097 - <unknown>
   7:     0x56061100f7d9 - <unknown>
   8:     0x56061100f511 - <unknown>
   9:     0x56061100d9fc - <unknown>
  10:     0x56061100f272 - <unknown>
  11:     0x56060f689823 - <unknown>
  12:     0x56060f6898fd - <unknown>
  13:     0x56061044d424 - <unknown>
  14:     0x560610405780 - <unknown>
  15:     0x56060f7d8d40 - <unknown>
  16:     0x56060f897392 - <unknown>
  17:     0x56060f8675a1 - <unknown>
  18:     0x56060f8688a3 - <unknown>
  19:     0x56060f7c5f83 - <unknown>
  20:     0x56060f874429 - <unknown>
  21:     0x560610ffeffb - <unknown>
  22:     0x56060f871065 - <unknown>
  23:     0x7f152380b290 - <unknown>
  24:     0x7f152380b34a - __libc_start_main
  25:     0x56060f689cc5 - <unknown>
  26:                0x0 - <unknown>
```

### Anything else?

no

**Comment by wez** [comment]
Likely a duplicate of:
*  https://github.com/wez/wezterm/issues/2445

**Comment by glyh** [comment]
I'm closing this in favor of that.

**Comment by glyh** [comment]
Here's the crash log with `WAYLAND_DEBUG=1`
<details>

```
[3432981.177]  -> wl_display@1.get_registry(new id wl_registry@2)
[3432981.210]  -> wl_display@1.sync(new id wl_callback@3)
[3432981.508] wl_display@1.delete_id(3)
[3432981.533] wl_registry@2.global(1, "wl_shm", 1)
[3432981.561]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[3432981.571] wl_registry@2.global(2, "wl_drm", 2)
[3432981.576] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 4)
[3432981.584] wl_registry@2.global(4, "wl_compositor", 5)
[3432981.595]  -> wl_registry@2.bind(4, "wl_compositor", 5, new id [unknown]@5)
[3432981.601] wl_registry@2.global(5, "wl_subcompositor", 1)
[3432981.609]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@6)
[3432981.615] wl_registry@2.global(6, "wl_data_device_manager", 3)
[3432981.622]  -> wl_registry@2.bind(6, "wl_data_device_manager", 3, new id [unknown]@7)
[3432981.628] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[3432981.634] wl_registry@2.global(8, "zxdg_output_manager_v1", 3)
[3432981.640] wl_registry@2.global(9, "org_kde_kwin_idle", 1)
[3432981.645] wl_registry@2.global(10, "ext_idle_notifier_v1", 1)
[3432981.651] wl_registry@2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[3432981.656] wl_registry@2.global(12, "zwlr_layer_shell_v1", 3)
[3432981.661] wl_registry@2.global(13, "xdg_wm_base", 2)
[3432981.666] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[3432981.672] wl_registry@2.global(15, "org_kde_kwin_server_decoration_manager", 1)
[3432981.677] wl_registry@2.global(16, "zxdg_decoration_manager_v1", 1)
[3432981.687]  -> wl_registry@2.bind(16, "zxdg_decoration_manager_v1", 1, new id [unknown]@8)
[3432981.694] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[3432981.698] wl_registry@2.global(18, "zwp_pointer_constraints_v1", 1)
[3432981.703] wl_registry@2.global(19, "wp_presentation", 1)
[3432981.708] wl_registry@2.global(20, "zwlr_output_manager_v1", 4)
[3432981.713] wl_registry@2.global(21, "zwlr_output_power_manager_v1", 1)
[3432981.719] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[3432981.724] wl_registry@2.global(23, "zwp_text_input_manager_v3", 1)
[3432981.729]  -> wl_registry@2.bind(23, "zwp_text_input_manager_v3", 1, new id [unknown]@9)
[3432981.739] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[3432981.745] wl_registry@2.global(25, "ext_session_lock_manager_v1", 1)
[3432981.749] wl_registry@2.global(26, "wp_drm_lease_device_v1", 1)
[3432981.754] wl_registry@2.global(27, "zwlr_export_dmabuf_manager_v1", 1)
[3432981.759] wl_registry@2.global(28, "zwlr_screencopy_manager_v1", 3)
[3432981.764] wl_registry@2.global(29, "zwlr_data_control_manager_v1", 2)
[3432981.769] wl_registry@2.global(30, "wp_viewporter", 1)
[3432981.773] wl_registry@2.global(31, "wp_single_pixel_buffer_manager_v1", 1)
[3432981.778] wl_registry@2.global(32, "wp_content_type_manager_v1", 1)
[3432981.783] wl_registry@2.global(33, "zxdg_exporter_v1", 1)
[3432981.788] wl_registry@2.global(34, "zxdg_importer_v1", 1)
[3432981.793] wl_registry@2.global(35, "zxdg_exporter_v2", 1)
[3432981.800] wl_registry@2.global(36, "zxdg_importer_v2", 1)
[3432981.803] wl_registry@2.global(37, "xdg_activation_v1", 1)
[3432981.810] wl_registry@2.global(38, "zwp_virtual_keyboard_manager_v1", 1)
[3432981.815] wl_registry@2.global(39, "zwlr_virtual_pointer_manager_v1", 2)
[3432981.820] wl_registry@2.global(40, "zwlr_input_inhibit_manager_v1", 1)
[3432981.824] wl_registry@2.global(41, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3432981.829] wl_registry@2.global(42, "wl_seat", 8)
[3432981.835]  -> wl_registry@2.bind(42, "wl_seat", 6, new id [unknown]@10)
[3432981.843] wl_registry@2.global(43, "zwp_pointer_gestures_v1", 3)
[3432981.848] wl_registry@2.global(44, "xwayland_shell_v1", 1)
[3432981.853] wl_registry@2.global(45, "zwp_primary_selection_device_manager_v1", 1)
[3432981.858] wl_registry@2.global(46, "wl_output", 4)
[3432981.866]  -> wl_registry@2.bind(46, "wl_output", 3, new id [unknown]@11)
[3432981.873] wl_callback@3.done(53878)
[3432981.881]  -> wl_display@1.sync(new id wl_callback@3)
[3432982.026] wl_display@1.delete_id(3)
[3432982.038] wl_shm@4.format(0)
[3432982.046] wl_shm@4.format(1)
[3432982.050] wl_shm@4.format(875709016)
[3432982.055] wl_shm@4.format(875708993)
[3432982.059] wl_shm@4.format(875710274)
[3432982.065] wl_shm@4.format(842094674)
[3432982.069] wl_shm@4.format(842088786)
[3432982.073] wl_shm@4.format(892426322)
[3432982.079] wl_shm@4.format(892420434)
[3432982.083] wl_shm@4.format(909199186)
[3432982.087] wl_shm@4.format(808665688)
[3432982.093] wl_shm@4.format(808665665)
[3432982.097] wl_shm@4.format(1211384408)
[3432982.101] wl_shm@4.format(1211384385)
[3432982.106] wl_shm@4.format(942948952)
[3432982.110] wl_shm@4.format(942948929)
[3432982.113] wl_seat@10.name("seat0")
[3432982.123] wl_seat@10.capabilities(2)
[3432982.131]  -> wl_data_device_manager@7.get_data_device(new id wl_data_device@12, wl_seat@10)
[3432982.141] wl_output@11.geometry(0, 0, 290, 180, 0, "California Institute of Technology", "0x076D", 0)
[3432982.151] wl_output@11.mode(1, 2560, 1600, 59994)
[3432982.156] wl_output@11.scale(2)
[3432982.161] wl_output@11.done()
[3432982.166] wl_callback@3.done(53878)
[3432982.177]  -> wl_registry@2.bind(45, "zwp_primary_selection_device_manager_v1", 1, new id [unknown]@3)
[3432982.189]  -> zwp_primary_selection_device_manager_v1@3.get_device(new id zwp_primary_selection_device_v1@13, wl_seat@10)
[3432982.202]  -> wl_seat@10.get_keyboard(new id wl_keyboard@14)
[3432982.213]  -> zwp_text_input_manager_v3@9.get_text_input(new id zwp_text_input_v3@15, wl_seat@10)
[3432982.256]  -> wl_shm@4.create_pool(new id wl_shm_pool@16, fd 5, 4096)
21:09:15.022  ERROR  env_bootstrap > panic at window/src/os/wayland/connection.rs:191:35 - called `Option::unwrap()` on a `None` value
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __libc_start_main
  19: <unknown>

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', window/src/os/wayland/connection.rs:191:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[3432983.763]  -> wl_shm_pool@16.destroy()

```

</details>

**Comment by wez** [comment]
That particular error suggests that none of the available wayland "seats" on your system has a pointer capability.
Can you tell me more about your system? Is there something unusual about the mouse/pointer input?

**Comment by glyh** [comment]
I'm on Arch Linux with the following packages. wlroots is forked to support HiDPI inxwayland, I don't know if that will affect wezterm. Up till now I don't have any problem with kitty/alacritty at least.
```
wayland xorg
xorg-xwayland-hidpi-xprop wlroots-hidpi-xprop-git
sway-git
```
