### ISSUE TITLE
Crash on startup "No OpenGL" panic (on macOS)

### ISSUE THREAD

**Issue by erf** [wez/wezterm#307]
## Describe the bug

`wezterm` suddenly started crashing on startup every time with the following log message :

```
 2020-10-25T22:18:37.329Z ERROR wezterm_gui::gui::termwindow > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 1680, pixel_height: 1075, dpi: 192 }
 2020-10-25T22:18:37.461Z ERROR wezterm_gui::gui::termwindow > failed to create OpenGLRenderState: Texture Size exceeded, need Some(256)
thread 'main' panicked at 'No OpenGL', wezterm-gui/src/gui/termwindow.rs:720:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 2020-10-25T22:18:37.566Z ERROR mux                          > read_pty EOF: pane_id 0
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:241:26
fatal runtime error: failed to initiate panic, error 5
zsh: abort      /Applications/WezTerm.app/wezterm
```

I also get the following notification:

```
Wezterm panic
No OpenGL
```

I am able to startup with no configuration, but i do get the following error messages:

```
 2020-10-25T22:21:23.265Z ERROR wezterm_gui::gui::termwindow > scale changed so resize to RowsAndCols { rows: 24, cols: 80 } Dimensions { pixel_width: 1280, pixel_height: 850, dpi: 192 }
 2020-10-25T22:21:23.430Z ERROR wezterm_gui::gui::termwindow > OpenGL initialized! ANGLE (Metal Renderer: Intel(R) Iris(TM) Plus Graphics 640) OpenGL ES 3.0.0 (ANGLE 2.1.0.8230df39a500) is_context_loss_possible=false
 2020-10-25T22:21:28.492Z ERROR wezterm_gui::gui::termwindow > grow texture atlas to 256
```

The last `ERROR` i get when i run the `ls` command.

I also get the follwing error after i quit (after running with no config):

```
 2020-10-25T22:26:37.738Z ERROR mux                          > read_pty EOF: pane_id 0
```

## Environment (please complete the following information):

 - OS: macOS ( 10.15.7 (19H2) )
 - Version: 20200909-002054-4c9af461-233-g198c4010

## To Reproduce

I just ran the app.

## Configuration

I only set `font_size = 13.0` to make it crash.

**Comment by wez** [comment]
Ooh, interesting.  I can reproduce this on linux with `font_size=33.0` on a regular dpi display.  Investigating!

**Comment by wez** [comment]
Fixed in master; the workaround for now (until a build shows up on the commit: https://github.com/wez/wezterm/runs/1306169739 or in the nightly downloads) is to use a smaller initial font size.
After the initial window is set up, you can increase the font size.
