### ISSUE TITLE
LoadLibrary failed with error 87: The parameter is incorrect

### ISSUE THREAD

**Issue by prabirshrestha** [wez/wezterm#40]
Doesn't work when using remote desktop. Alacritty also seems to face the same issue and there is more details here https://github.com/jwilm/alacritty/issues/1976

New windows terminal works so could be an issue with opengl.

**Comment by wez** [comment]
I suspect that the best way to resolve this would be to build a DirectWrite frontend for wezterm that can target Direct2D and fallback easily to software rendering that is compatible with RDP.

It's not high on my list of priorities at the moment.

**Comment by prabirshrestha** [comment]
Yes. Most likely would need to do that. Another option is vulkan but haven't tried a simple hello world yet so not sure if that has the same issue as opengl.

Still on the quest for a single terminal emulator that works on all 3 OS.

**Comment by wez** [comment]
I just pushed to master the option of using a new `software` rendering front-end.  You can enable it either from the command line:

```
wezterm start --front-end software
```

(if you are building it with cargo: `cargo run --release -- start --front-end software`)

Or you can configure it so that the `software` front-end is always used by setting it in your `wezterm.toml` configuration file on the remote host:

```
front_end = "Software"
```

The `software` front-end doesn't use the `winit` ecosystem to set up windowing and may have subtle behavioral differences when compared to the default opengl front-end.

Because the `software` front-end uses the CPU to render the display, the CPU utilization is higher than the opengl front-end; you can expect the CPU usage to scale with the size of the window and the rate at which the window contents change.

**Comment by prabirshrestha** [comment]
Do you have a build I can try? I'm not being able to compile in rust 1.38. Getting error when compiling feetype. Also might be good to checkin the Cargo.lock file.

I recently got another machine which works well with opengl and doesn't have the LoadLibrary issue.

**Comment by prabirshrestha** [comment]
Here is the log. Fails with same error on both my windows machines. 

```
error: failed to run custom build command for `freetype v0.1.0 (D:\tmp\wezterm\deps\freetype)`

Caused by:
  process didn't exit successfully: `d:\tmp\wezterm\target\release\build\freetype-43bfbb9c9f2bcf9a\build-script-build` (exit code: 101)
--- stdout
running: "cmake" "d:\\tmp\\wezterm\\target\\release\\build\\freetype-5fb4c4c624b58dda\\out\\zlib-src\\zlib" "-G" "Visual Studio 15 2017" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=d:\\tmp\\wezterm\\target\\release\\build\\freetype-5fb4c4c624b58dda\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"

--- stderr
CMake Error: The source directory "D:/tmp/wezterm/target/release/build/freetype-5fb4c4c624b58dda/out/zlib-src/zlib" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', C:\Users\prshrest\.cargo\registry\src\github.com-1ecc6299db9ec823\cmake-0.1.42\src\lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by wez** [comment]
I think you need to run `git submodule update --init` to resolve that issue!

I just pushed a commit to unblock some clippy issues; that should allow the next nightly to build and push binaries as a nightly release download for tomorrow night.

**Comment by wez** [comment]
Looks like this got built and you can now click the nightly download button on https://wezfurlong.org/wezterm/installation.html

**Comment by prabirshrestha** [comment]
Was able to compile but getting different error now.

<details><summary>Error</summary>

```
[master] d:\tmp\wezterm>cargo run --release -- start --front-end software
   Compiling window v0.1.0 (D:\tmp\wezterm\window)
   Compiling wezterm v0.1.0 (D:\tmp\wezterm)
    Finished release [optimized + debuginfo] target(s) in 53.76s
     Running `target\release\wezterm.exe start --front-end software`
 ERROR wezterm::frontend::software::termwindow > TermWindow::new_window called with mux_window_id 0
 ERROR wezterm                                 > domain 0 state Attached
 ERROR wezterm                                 > domain 1 state Detached
 ERROR wezterm::frontend::software::termwindow > paint_tab elapsed=2.4657ms
thread 'main' panicked at 'phys_row called with negative row -1', term\src\screen.rs:145:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: process didn't exit successfully: `target\release\wezterm.exe start --front-end software` (exit code: 1)

[master] d:\tmp\wezterm>set RUST_BACKTRACE=1

[master] d:\tmp\wezterm>cargo run --release -- start --front-end software
    Finished release [optimized + debuginfo] target(s) in 5.69s
     Running `target\release\wezterm.exe start --front-end software`
 ERROR wezterm::frontend::software::termwindow > TermWindow::new_window called with mux_window_id 0
 ERROR wezterm                                 > domain 1 state Detached
 ERROR wezterm                                 > domain 0 state Attached
thread 'main' panicked at 'phys_row called with negative row -1', term\src\screen.rs:145:9
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:339
   8: term::terminalstate::TerminalState::set_cursor_pos
             at .\term\src\terminalstate.rs:0
   9: term::terminalstate::TerminalState::resize
             at .\term\src\terminalstate.rs:1032
  10: wezterm::frontend::guicommon::localtab::{{impl}}::resize
             at .\src\frontend\guicommon\localtab.rs:54
  11: wezterm::frontend::software::termwindow::TermWindow::scaling_changed
             at .\src\frontend\software\termwindow.rs:571
  12: wezterm::frontend::software::termwindow::{{impl}}::resize
             at .\src\frontend\software\termwindow.rs:192
  13: window::os::windows::window::wm_size
             at .\window\src\os\windows\window.rs:386
  14: window::os::windows::window::do_wnd_proc
             at .\window\src\os\windows\window.rs:766
  15: window::os::windows::window::wnd_proc::{{closure}}
             at .\window\src\os\windows\window.rs:795
  16: std::panicking::try::do_call<closure-0,isize>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:296
  17: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  18: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:275
  19: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panic.rs:394
  20: window::os::windows::window::wnd_proc
             at .\window\src\os\windows\window.rs:794
  21: CallWindowProcW
  22: SendMessageW
  23: GetWindowTextW
  24: MapWindowPoints
  25: IsCompositionActive
  26: IsCompositionActive
  27: GetWindowTextW
  28: window::os::windows::window::wnd_proc::{{closure}}::{{closure}}
             at .\window\src\os\windows\window.rs:796
  29: core::option::Option<isize>::unwrap_or_else
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\option.rs:419
  30: window::os::windows::window::wnd_proc::{{closure}}
             at .\window\src\os\windows\window.rs:795
  31: std::panicking::try::do_call<closure-0,isize>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:296
  32: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  33: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panicking.rs:275
  34: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\panic.rs:394
  35: window::os::windows::window::wnd_proc
             at .\window\src\os\windows\window.rs:794
  36: CallWindowProcW
  37: DispatchMessageW
  38: MBToWCSEx
  39: KiUserCallbackDispatcher
  40: NtUserPeekMessage
  41: PeekMessageW
  42: PeekMessageW
  43: window::os::windows::connection::{{impl}}::run_message_loop
             at .\window\src\os\windows\connection.rs:39
  44: wezterm::run_terminal_gui
             at .\src\main.rs:504
  45: wezterm::run
             at .\src\main.rs:579
  46: wezterm::main
             at .\src\main.rs:508
  47: std::rt::lang_start::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  48: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\ops\function.rs:235
  49: core::ops::function::FnOnce::call_once<closure-0,()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  50: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  51: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  52: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  53: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  54: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  55: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  56: main
  57: invoke_main
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  58: __scrt_common_main_seh
             at d:\agent\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  59: BaseThreadInitThunk
  60: RtlUserThreadStart
error: process didn't exit successfully: `target\release\wezterm.exe start --front-end software` (exit code: 1)
```
</details>

**Comment by wez** [comment]
Current master now includes an OpenGL frontend that falls back to the Software frontend if OpenGL is not available.  I'm planning on making that the default front end and to soon remove the Glutin front end.

You can download a build from here:
https://github.com/wez/wezterm/suites/282865528/artifacts/185144

The usage instructions are the same as per https://github.com/wez/wezterm/issues/40#issuecomment-536248350 but I'd suggest using `OpenGL` instead of `Software` to exercise the fallback path.

**Comment by wez** [comment]
I removed the older winit/glutin frontend in master; the default is now our dynamically loaded glium opengl frontend with automatic fallback to the software renderer.

I'm going to mark this issue as closed.
