### ISSUE TITLE
Running `wezterm imgcat` too rapidly on any large enough image causes errors

### ISSUE THREAD

**Issue by ir-ae** [wez/wezterm#4029]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

wezterm 20230717-105553-e0484104

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Running `wezterm imgcat` on a large image too quickly in succession causes many errors:
 ("large" seems to be anything over 300kB) 
```
13:54:35.431  ERROR  env_bootstrap > panic at wezterm\src\main.rs:377:10 - attempt to divide by zero
   0: git_filter_source_repo
   1: git_filter_source_repo
   2: <unknown>
   3: git_tree_entry_filemode_raw
   4: git_tree_entry_filemode_raw
   5: git_tree_entry_filemode_raw
   6: git_tree_entry_filemode_raw
   7: git_credential_username_new
   8: git_credential_username_new
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: git_tree_entry_filemode_raw
  15: <unknown>
  16: git_credential_username_new
  17: BaseThreadInitThunk
  18: RtlUserThreadStart

thread 'main' panicked at 'attempt to divide by zero', wezterm\src\main.rs:377:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
13:54:35.585  ERROR  wezterm > no size information available: no size information available; terminating
13:54:35.743  ERROR  wezterm > no size information available: no size information available; terminating
```

### To Reproduce

On a 300kB+ image run some equivalent of 
```zsh
for i in {1..10}; do wezterm imgcat "name_of_large_file.jpg"; done
``` 
Running it slowly enough succeeds with no errors:
```zsh
for i in {1..10}; do wezterm imgcat "name_of_large_file.jpg"; sleep 1; done
``` 

### Configuration

no config

### Expected Behavior

Display the image without error.

**Comment by jadijadi** [comment]
Was not able to reproduce on Mac, wezterm 20230712-072601-f4abf8fd, a few ~1M files and 100 repetition. 
Might be a Win, older version issue.

**Comment by wez** [comment]
The root cause is that conpty (the PTY layer in windows that sits between the `wezterm imgcat` process and the actual terminal emulator) is sometimes slow to process certain types of escape sequences that it doesn't fully understand, so in this case, when `imgcat` is probing to determine the terminal pixel geometry, it gets back 0 values and that leads to the divide by zero.

So this is a 2-part issue:

* Replace the divide by zero panic with a nicer error message
* Do something to adjust the timing of the probing to potentially increase the chances of success

**Comment by yermulnik** [comment]
I'm hitting the `no size information available` under `screen` on Ubuntu 22.04:
```shell
> screen --version
Screen version 4.09.00 (GNU) 30-Jan-22

> wezterm --version
wezterm 20240203-110809-5046fc22

> wezterm imgcat ~/tmp/1081547.png
12:42:57.928  ERROR  wezterm > no size information available: no size information available; terminating
```

Should I file a separate issue for this?
