### ISSUE TITLE
Crash with wgpu on Fedora 39

### ISSUE THREAD

**Issue by ardrigh** [wez/wezterm#4825]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

DE: GNOME 45.3
WM: Mutter (Wayland)

### WezTerm version

wezterm 20240120_230923_1635d952

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I updated Wezterm nightly package using the new COPR repository for Fedora 39.

I opened Wezterm as normal and started editing small Terraform HCL files in Helix Editor.

When I was doing some cut and paste operations, Wezterm crashed.

I have been using Wezterm for a while now, and this is the first time I have seen it crash.

### To Reproduce

Start wezterm, start editing files

### Configuration

local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.color_scheme = 'Oceanic-Next'
config.enable_kitty_keyboard = true
config.font = wezterm.font_with_fallback {
  {
    family = 'FiraCode',
    harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
  }
}
config.font_rules = {
  {
    intensity = 'Half',
    italic = false,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Regular',
      style = 'Normal',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
  {
    intensity = 'Half',
    italic = true,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Regular',
      style = 'Italic',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
  {
    intensity = 'Normal',
    italic = false,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Medium',
      style = 'Normal',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
  {
    intensity = 'Normal',
    italic = true,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Medium',
      style = 'Italic',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
  {
    intensity = 'Bold',
    italic = false,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Bold',
      style = 'Normal',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
  {
    intensity = 'Bold',
    italic = true,
    font = wezterm.font {
      family = 'FiraCode',
      weight = 'Bold',
      style = 'Italic',
      harfbuzz_features = { 'zero', 'ss01', 'ss02', 'ss03', 'ss04', 'ss05', 'ss06', 'ss07', 'ss08', 'ss09', 'cv01', 'cv02', 'cv04', 'cv07', 'cv15', 'cv17', 'cv18', 'cv24', 'cv25', 'cv26', 'cv27', 'cv28', 'cv29', 'cv30', 'cv31', 'cv32' },
    },
  },
}
config.font_size = 10
config.inactive_pane_hsb = {
  saturation = 0.7,
  brightness = 0.6,
}
config.scrollback_lines = 10000

return config

### Expected Behavior

Wezterm will not crash

### Logs

org.wezfurlong.wezterm.desktop[23895]: 16:32:15.815  ERROR  wgpu::backend::wgpu_core > Handling wgpu errors as fatal by default
org.wezfurlong.wezterm.desktop[23895]: 16:32:15.858  ERROR  env_bootstrap            > panic at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/wgpu_core.rs:3009:5 - !?
org.wezfurlong.wezterm.desktop[23895]:    0: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    1: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    2: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    3: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    4: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    5: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    6: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    7: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    8: <unknown>
org.wezfurlong.wezterm.desktop[23895]:    9: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   10: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   11: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   12: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   13: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   14: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   15: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   16: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   17: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   18: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   19: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   20: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   21: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   22: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   23: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   24: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   25: <unknown>
org.wezfurlong.wezterm.desktop[23895]:   26: __libc_start_call_main
org.wezfurlong.wezterm.desktop[23895]:   27: __libc_start_main_impl
org.wezfurlong.wezterm.desktop[23895]:   28: <unknown>
org.wezfurlong.wezterm.desktop[23895]: thread 'main' panicked at /builddir/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.0/src/backend/wgpu_core.rs:3009:5:
org.wezfurlong.wezterm.desktop[23895]: wgpu error: Validation Error
org.wezfurlong.wezterm.desktop[23895]: Caused by:
org.wezfurlong.wezterm.desktop[23895]:     In Device::create_buffer
org.wezfurlong.wezterm.desktop[23895]:       note: label = `Vertex Buffer`
org.wezfurlong.wezterm.desktop[23895]:     Not enough memory left.
org.wezfurlong.wezterm.desktop[23895]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
org.wezfurlong.wezterm.desktop[23895]: thread panicked while processing panic. aborting.

**Comment by wez** [comment]
I just updated wgpu to 0.19 today and it seems very particular about device limits.
For now, I suggest setting `front_end = "OpenGL"` as a workaround for this.

**Comment by ardrigh** [comment]
I will add that to my config

**Comment by wez** [comment]
If you'd like to help get to the root cause for this, if you can build wezterm from source in debug mode (eg: follow the build from source instructions, but not using `--release`  when building), and can reproduce and get a better trace, that will help figure out what exactly wgpu doesn't like

**Comment by ardrigh** [comment]
I do have rust and cargo installed, so I'll take a look

**Comment by wez** [comment]
I've reverted the wgpu 0.19 upgrade in `main`.

**Comment by wez** [comment]
I suspect that the trace here is the same as the one in:
https://github.com/wez/wezterm/issues/4826#issuecomment-1902812165
