### ISSUE TITLE
"Open in WezTerm" is not added in Ubuntu 20.04 Nautilus Context Menu. (TypeError: super() takes at least 1 argument (0 given))

### ISSUE THREAD

**Issue by fs000x** [wez/wezterm#5513]
### What Operating System(s) are you seeing this problem on?

Linux X11

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

"Open in WezTerm" is not added in nautilus context menu.

nautilus use python2 default in Ubuntu 20.04, super().__init__() is python3 syntax

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/wezterm-nautilus.py", line 25, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

### Configuration

no config

### Logs

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/wezterm-nautilus.py", line 25, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by fs000x** [comment]
resolved by install python3-nautilus

```sh
$ sudo apt remove python-nautilus
$ sudo apt install python3-nautilus
```
