### ISSUE TITLE
Panic on mouse right-click on the tabs in the tab bar

### ISSUE THREAD

**Issue by carmelopellegrino** [wez/wezterm#552]
## Describe the bug
If I right-click on a tab, the tab selector show up. If I right-click again on any of the tabs wezterm panics.

Here is the panic traces:
- macOS Big Sur
```
 2021-03-17T11:56:11.085Z INFO  wezterm_mux_server_impl::local > setting up xxxxxxx/.local/share/wezterm/gui-sock-74440
 2021-03-17T11:56:11.259Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Apple M1 4.1 Metal - 70.12.7 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd
 2021-03-17T11:56:11.429Z WARN  wezterm_term::terminalstate    > Unhandled OSC
122 >
thread 'main' panicked at 'already borrowed: BorrowMutError', mux/src/lib.rs:364:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
- ArchLinux:
```
2021-03-17T11:58:38.844Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-1035717
 2021-03-17T11:58:39.888Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2) OpenGL ES 3.0 Mesa 20.3.2 is_context_loss_possible=false wezterm version: 20210314-114017-04b7cedd
thread 'main' panicked at 'already borrowed: BorrowMutError', mux/src/lib.rs:364:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Seems like rust is panicking to prevent mutex deadlock or something similar.

## Environment:

 - OS: Linux X11, macOS
 - Version (on both OSes):
```$ wezterm -V
wezterm 20210314-114017-04b7cedd
```
 - The active keyboard layout name: US

## To Reproduce
Just open wezterm with tab bar active and right-click twice the current tab.

## Configuration
Probably not relevant, though I put it here:

```lua
return {
  font = wezterm.font("Fira Code"),
  font_size = 11.0,
  font_rules = {
    {
      italic = true,
      intensity = "Bold",
      font = wezterm.font("Victor Mono", {italic=true, bold=true}),
    },
    {
      intensity = "Bold",
      font = wezterm.font("Fira Code", {bold=true}),
    },
    {
      italic = true,
      font = wezterm.font("Victor Mono", {italic=true}),
    },
  },
  font_antialias = "Greyscale",
  font_hinting = "Full",
  bold_brightens_ansi_colors = true,
  line_height = 1.1,
  scrollback_lines = 100000,
  enable_tab_bar = true,
  window_background_opacity = 0.95,
  color_scheme = "fall",

  color_schemes = {
    ["fall"] = {
      foreground = "#aaaaaa",
      background = "#162228",
      cursor_bg = "#666666",
      cursor_border = "#aaaaaa",
      cursor_fg = "#aaaaaa",
      -- selection_bg = "#b5d5ff",
      -- selection_fg = "#000000",

      ansi = {"#202020","#ff6565","#93d44f","#eab93d","#204a87","#ce5c00","#89b6e2","#cccccc"},
      brights = {"#606060","#ff8d8d","#c8e7a8","#ffc123","#3465a4","#f57900","#46a4ff","#ffffff"},
    },
  },

  keys = {
    -- Make Option-Left equivalent to Alt-b; backward-word
    {key="LeftArrow", mods="OPT", action=wezterm.action{SendString="\x1bb"}},
    -- Make Option-Right equivalent to Alt-f; forward-word
    {key="RightArrow", mods="OPT", action=wezterm.action{SendString="\x1bf"}},
    -- Scroll tabs with CMD+Arrow and CTRL+SHIFT+Arrow
    {key="RightArrow", mods="CMD", action=wezterm.action{ActivateTabRelative=1}},
    {key="LeftArrow", mods="CMD", action=wezterm.action{ActivateTabRelative=-1}},
    {key="RightArrow", mods="CTRL|SHIFT", action=wezterm.action{ActivateTabRelative=1}},
    {key="LeftArrow", mods="CTRL|SHIFT", action=wezterm.action{ActivateTabRelative=-1}},
    -- Bind to Alt+Arrow
    {key="UpArrow", mods="OPT", action=wezterm.action{SendString="\x1b[1;3A"}},
    {key="DownArrow", mods="OPT", action=wezterm.action{SendString="\x1b[1;3B"}},
    -- Scroll to prompt
    {key="UpArrow", mods="SHIFT", action=wezterm.action{ScrollToPrompt=-1}},
    {key="DownArrow", mods="SHIFT", action=wezterm.action{ScrollToPrompt=1}},
    -- Scroll one line
    {key="UpArrow", mods="CTRL|SHIFT", action=wezterm.action{ScrollByLine=-1}},
    {key="DownArrow", mods="CTRL|SHIFT", action=wezterm.action{ScrollByLine=1}},  }
}
```

## Expected behaviour
Not to panic :) A valid option could be to go back to the previously active tab.

**Comment by carmelopellegrino** [comment]
sorry, just found this is duplicate of issue #542
