### ISSUE TITLE
`wezterm imgcat` crashes when running in tmux

### ISSUE THREAD

**Issue by hktonylee** [wez/wezterm#5522]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

I create a tmux session first. (`tmux`)

Then run this command in the tmux session `/Applications/WezTerm.app/Contents/MacOS/wezterm imgcat ~/Desktop/Shell\ Init\ Scripts.png`

It will throw the following error

```
11:04:32.657  ERROR  env_bootstrap > panic at wezterm/src/main.rs:383:10 - attempt to divide by zero
   0: backtrace::capture::Backtrace::create
   1: backtrace::capture::Backtrace::new
   2: env_bootstrap::register_panic_hook::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic_handler::{{closure}}
   5: std::sys_common::backtrace::__rust_end_short_backtrace
   6: _rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: wezterm::ImgCatCommand::compute_image_cell_dimensions
  10: wezterm::run
  11: wezterm::main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: std::rt::lang_start_internal
  15: std::rt::lang_start
  16: _main

thread 'main' panicked at wezterm/src/main.rs:383:10:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Re-run with `RUST_BACKTRACE=full` will show this:

<img width="1582" alt="image" src="https://github.com/wez/wezterm/assets/587925/78853374-016e-4a8c-83d7-cc02ffedb7af">

### Configuration

no config

### Expected Behavior

It shouldn't crash I guess

### Logs

﻿

**Comment by ArchWand** [comment]
Hi, to my understanding it looks like this should only happen if either the image or the terminal has a height and/or width of 0; can you upload the image you used as well?

**Comment by hktonylee** [comment]
(It seems my previous comment failed to upload :( I just checked and realized this)

This is the image. A normal PNG. I can display it with `wezterm imgcat` when it's not in tmux session.

![Shell Init Scripts](https://github.com/user-attachments/assets/1cbd6c64-a0fc-48c3-ac49-442a511c7211)

**Comment by bobby-b-song** [comment]
Getting the same error, remote running Ubuntu 20.04, local running Windows 11 both with wezterm nightly. Without tmux works file while with tmux errors out with diving by zero. 

![Image](https://github.com/user-attachments/assets/57c9779f-0b65-4589-bf85-a5da2674a519)

**Comment by bobby-b-song** [comment]
Update: bumping tmux from 3.0 to 3.5a fixes this issue
