### ISSUE TITLE
Panic after failing to load fallback font

### ISSUE THREAD

**Issue by 0f-0b** [wez/wezterm#6157]
### What Operating System(s) are you seeing this problem on?

macOS

### WezTerm version

20240915-153243-2d0c5cdd

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

WezTerm panics shortly after failing to load a fallback font.

### To Reproduce

1. Install some font, say Ubuntu Mono.

   ```sh
   brew install font-ubuntu-mono
   ```

2. Start WezTerm with the following command. Don't type anything yet in the new window.

   ```sh
   wezterm start -- lua -e 'io.read(); print(utf8.char(0x10000)); io.read()'
   ```

3. Uninstall the font.

   ```sh
   brew uninstall font-ubuntu-mono
   ```

4. Switch to the new window and press return.

### Configuration

```lua
local wezterm = require "wezterm"

return { font = wezterm.font_with_fallback { "JetBrains Mono", "Ubuntu Mono" } }
```

### Expected Behavior

No panic.

### Logs

```log
02:56:48.824  ERROR  wezterm_font::shaper::harfbuzz > load_fallback

Caused by:
    0: face_from_locator(FontDataHandle { source: OnDisk { path: "/Users/ud2/Library/Fonts/UbuntuMono-Regular.ttf" }, index: 0, variation: 0, origin: CoreText, coverage: None })
    1: opening file /Users/ud2/Library/Fonts/UbuntuMono-Regular.ttf
    2: No such file or directory (os error 2) for "𐀀"
02:56:48.871  ERROR  env_bootstrap                  > panic at wezterm-font/src/shaper/harfbuzz.rs:468:28 - !?
   0: backtrace::capture::Backtrace::new
   1: env_bootstrap::register_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_fmt
   7: core::str::slice_error_fail_rt
   8: core::str::slice_error_fail
   9: wezterm_font::shaper::harfbuzz::HarfbuzzShaper::do_shape
  10: wezterm_font::shaper::harfbuzz::HarfbuzzShaper::do_shape
  11: <wezterm_font::shaper::harfbuzz::HarfbuzzShaper as wezterm_font::shaper::FontShaper>::shape
  12: wezterm_font::LoadedFont::shape
  13: wezterm_gui::termwindow::render::<impl wezterm_gui::termwindow::TermWindow>::cached_cluster_shape
  14: wezterm_gui::termwindow::render::screen_line::<impl wezterm_gui::termwindow::TermWindow>::render_screen_line
  15: <wezterm_gui::termwindow::render::pane::<impl wezterm_gui::termwindow::TermWindow>::paint_pane::LineRender as mux::pane::WithPaneLines>::with_lines_mut
  16: wezterm_term::screen::Screen::with_phys_lines_mut
  17: <mux::localpane::LocalPane as mux::pane::Pane>::with_lines_mut
  18: wezterm_gui::termwindow::render::paint::<impl wezterm_gui::termwindow::TermWindow>::paint_pass
  19: wezterm_gui::termwindow::render::paint::<impl wezterm_gui::termwindow::TermWindow>::paint_impl
  20: wezterm_gui::termwindow::TermWindow::do_paint
  21: wezterm_gui::termwindow::TermWindow::dispatch_window_event
  22: wezterm_gui::termwindow::TermWindow::new_window::{{closure}}::{{closure}}
  23: window::WindowEventSender::dispatch
  24: window::os::macos::window::WindowView::draw_rect
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: <unknown>
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: <window::os::macos::connection::Connection as window::connection::ConnectionOps>::run_message_loop
  42: wezterm_gui::run_terminal_gui
  43: wezterm_gui::main
  44: std::sys::backtrace::__rust_begin_short_backtrace
  45: std::rt::lang_start::{{closure}}
  46: std::rt::lang_start_internal
  47: _main

thread 'main' panicked at wezterm-font/src/shaper/harfbuzz.rs:468:28:
byte index 4 is out of bounds of `�`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
02:56:48.874  ERROR  env_bootstrap                  > panic at library/core/src/panicking.rs:221:5 - panic in a function that cannot unwind
   0: backtrace::capture::Backtrace::new
   1: env_bootstrap::register_panic_hook::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::begin_panic_handler::{{closure}}
   4: std::sys::backtrace::__rust_end_short_backtrace
   5: _rust_begin_unwind
   6: core::panicking::panic_nounwind_fmt
   7: core::panicking::panic_nounwind
   8: core::panicking::panic_cannot_unwind
   9: window::os::macos::window::WindowView::draw_rect
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <window::os::macos::connection::Connection as window::connection::ConnectionOps>::run_message_loop
  27: wezterm_gui::run_terminal_gui
  28: wezterm_gui::main
  29: std::sys::backtrace::__rust_begin_short_backtrace
  30: std::rt::lang_start::{{closure}}
  31: std::rt::lang_start_internal
  32: _main

thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:        0x101e97f8c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h243268f17d714c7f
   1:        0x101ebbae4 - core::fmt::write::hb3cfb8a30e72d7ff
   2:        0x101e92e34 - std::io::Write::write_fmt::hfb2314975de9ecf1
   3:        0x101e99538 - std::panicking::default_hook::{{closure}}::h14c7718ccf39d316
   4:        0x101e9915c - std::panicking::default_hook::hc62e60da3be2f352
   5:        0x100957bf8 - env_bootstrap::register_panic_hook::{{closure}}::h34e99460686abe9b
   6:        0x101e9a03c - std::panicking::rust_panic_with_hook::h09e8a656f11e82b2
   7:        0x101e99924 - std::panicking::begin_panic_handler::{{closure}}::h1230eb3cc91b241c
   8:        0x101e98418 - std::sys::backtrace::__rust_end_short_backtrace::hc3491307aceda2c2
   9:        0x101e99614 - _rust_begin_unwind
  10:        0x101f55d4c - core::panicking::panic_nounwind_fmt::h91ee161184879b56
  11:        0x101f55dc4 - core::panicking::panic_nounwind::heab7ebe7a6cd845c
  12:        0x101f55eb0 - core::panicking::panic_cannot_unwind::hedc43d82620205bf
  13:        0x10131ef38 - window::os::macos::window::WindowView::draw_rect::h26e718bfe7a6dc3d
  14:        0x194dd9608 - <unknown>
  15:        0x19902ae50 - <unknown>
  16:        0x1991afce8 - <unknown>
  17:        0x19900d874 - <unknown>
  18:        0x19479fac8 - <unknown>
  19:        0x1951604e4 - <unknown>
  20:        0x190e1887c - <unknown>
  21:        0x190e18768 - <unknown>
  22:        0x190e17d94 - <unknown>
  23:        0x190e17434 - <unknown>
  24:        0x19b5c119c - <unknown>
  25:        0x19b5c0fd8 - <unknown>
  26:        0x19b5c0d30 - <unknown>
  27:        0x194676cc8 - <unknown>
  28:        0x194e6d4d0 - <unknown>
  29:        0x194669ffc - <unknown>
  30:        0x101337604 - <window::os::macos::connection::Connection as window::connection::ConnectionOps>::run_message_loop::h3d4bccd14898f6ac
  31:        0x100934084 - wezterm_gui::run_terminal_gui::he6613c3ae719542c
  32:        0x100935bec - wezterm_gui::main::h40edf2878a0a1d20
  33:        0x1006e0d28 - std::sys::backtrace::__rust_begin_short_backtrace::h62977bffe24f0ef3
  34:        0x100814a94 - std::rt::lang_start::{{closure}}::hbe077c6642ae35f8
  35:        0x101e8b5d4 - std::rt::lang_start_internal::hdd117cb81a316264
  36:        0x10093bed8 - _main
thread caused non-unwinding panic. aborting.
```

**Comment by luizribeiro** [comment]
This happened to me on macOS a few weeks ago with `20260707-093716-fff02ca5`, same panic site as the original report but a different way of losing the font: macOS rotated the hash-named MobileAsset directory backing PingFang out from under a long-running process (8 days uptime):

```
1: opening file /System/Library/AssetsV2/com_apple_MobileAsset_Font8/86ba2c91….asset/AssetData/PingFang.ttc
2: No such file or directory (os error 2) for "缓"
panic at wezterm-font/src/shaper/harfbuzz.rs:468:28
```

#7963 looks like the same crash on Windows via a permission error, so any `load_fallback` failure reaches this on both platforms.

I put Opus 5 to investigate this and this is our understanding of what's going on. The failing load itself doesn't panic. When a fallback fails, `do_shape` recovers by shaping a small placeholder string, but hands harfbuzz a byte range that belongs to the original line, not to the placeholder (`harfbuzz.rs:494-508`). Nothing checks that range: `hb_buffer_add_utf8` never compares `item_offset` against the text length, so harfbuzz reads past the end of the placeholder allocation, and the bogus cluster values it returns are what blow up at line 468. Depending on heap layout that's a silent out of bounds read or a SIGSEGV instead of a panic.

This reproduces without a GUI. luizribeiro/wezterm@70ecb1cf466c6e0e614cf76a0f518313b98e3e79 is a regression test that resolves a real font and repoints `handle.source` at a missing path; it fails with `end byte index 7 is out of bounds for string of length 3` at the same line.

On PR #8058: it fixes this trigger (the test above passes with it) but not the recovery path itself. Any error raised after the face opens still lands there. luizribeiro/wezterm@cca2f4603842f8734fd546e46a743ea67d22b3de is a second test where the fallback's file opens fine but fails to size, via the ordinary `scale` config parameter, and it panics identically with #8058 applied. So that PR fixes the reported repro but shouldn't fully close this issue.

The fix I'd make: shape the placeholder in its own coordinates (`0..question.len()`, no `presentation_width`) and map the resulting glyphs back onto the original cluster's byte offset and cell width; separately, validate ranges in `hbwrap.rs` `add_str` so a bad range anywhere becomes an error instead of an over-read. If we don't think this should be part of #8058, I'd be happy to put up another PR on top of it.
