### ISSUE TITLE
wezterm crashes when unplugging external monitor

### ISSUE THREAD

**Issue by daniel-j-h** [wez/wezterm#6480]
### What Operating System(s) are you seeing this problem on?

Linux Wayland

### Which Wayland compositor or X11 Window manager(s) are you using?

Fedora Linux 41 (Workstation Edition) with (default): Wayland, Gnome 47, Linux 6.11.10-300.fc41.x86_64

This happens on a fresh, latest, default Fedora installation I just set up yesterday.

### WezTerm version

20240203-110809-5046fc22

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

No, and I'll explain why below

### Describe the bug

I'm on a laptop and have an external monitor attached. I use this external monitor with wezterm and have a few smaller apps displaying on the laptop screen at the same time. When I then unplug the external monitor where wezterm is currently displaying, wezterm crashes hard.

### To Reproduce

1. Plug in external monitor
2. Move wezterm on the external monitor's display
3. Unplug external monitor

### Configuration

I do have a custom config but I just reproduced the crash when unplugging the monitor without a wezterm.lua config.

### Expected Behavior

wezterm doesn't crash when displays get attached or detached

### Logs

Here is the crash log I could find, hope this helps. Let me know if I can provide more information as I can reproduce it.

```
User Logs:
--Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: wp_linux_drm_syncobj_surface_v1@71: error 2: Explicit Sync only supported on dmabuf buffers
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: 11:31:47.274  ERROR  wgpu_hal::vulkan::adapter > get_physical_device_surface_present_modes: ERROR_SURFACE_LOST_KHR
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: 11:31:47.274  ERROR  wgpu_hal::vulkan::adapter > get_physical_device_surface_formats: ERROR_SURFACE_LOST_KHR
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: 11:31:47.280  ERROR  env_bootstrap             > panic at /run/build/wezterm/cargo/vendor/wgpu-0.18.0/src/backend/direct.rs:778:18 - !?
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    0: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    1: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    2: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    3: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    4: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    5: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    6: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    7: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    8: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:    9: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   10: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   11: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   12: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   13: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   14: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   15: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   16: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   17: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   18: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   19: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   20: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   21: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   22: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   23: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   24: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   25: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   26: __libc_start_main
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:   27: <unknown>
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: thread 'main' panicked at /run/build/wezterm/cargo/vendor/wgpu-0.18.0/src/backend/direct.rs:778:18:
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: Error in Surface::configure: Validation Error
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: Caused by:
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]:     Requested format Bgra8UnormSrgb is not in list of supported formats: []
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 11 11:31:47 fedora org.wezfurlong.wezterm.desktop[92609]: thread panicked while processing panic. aborting.
--

```

**Comment by daniel-j-h** [comment]
Aha! Because the crash seems to come from the wgpu implementation (see above)

    /run/build/wezterm/cargo/vendor/wgpu-0.18.0/src/backend/direct.rs

I gave the OpenGL front end a try, as in

    config.front_end = 'OpenGL'

in `wezterm.lua` as documented in https://wezfurlong.org/wezterm/config/lua/config/front_end.html

and that at least seems to be a viable workaround for now!
