### ISSUE TITLE
`wezterm start -- cmd.exe` or `wezterm -e cmd.exe` failing on Windows

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [wez/wezterm#6499]
### What Operating System(s) are you seeing this problem on?

Windows

### WezTerm version

20241205-083533-6f375e29

### Did you try the latest nightly build to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version of the nightly that I tried

### Describe the bug

Whenever _WezTerm_ is started with the `start` (or `-e`) argument, it crashes:

```bat
rem error
wezterm start -- cmd
rem also error
wezterm -e cmd
```

The error message is:

```console
14:08:58.665  ERROR  env_bootstrap > panic at pty\src\cmdbuilder.rs:598:67 - !?
   0: git_odb_object_size
   1: git_odb_object_size
   2: git_filter_source_path
   3: git_odb_object_size
   4: git_odb_object_size
   5: git_odb_object_size
   6: git_odb_object_size
   7: cairo_raster_source_pattern_set_snapshot
   8: git_odb_object_size
   9: cairo_raster_source_pattern_set_snapshot
  10: git_odb_object_size
  11: git_odb_object_size
  12: git_odb_object_size
  13: git_patch_owner
  14: git_filter_source_path
  15: git_filter_source_path
  16: git_filter_source_path
  17: <unknown>
  18: git_odb_object_size
  19: git_odb_object_size
  20: git_filter_source_path
  21: git_filter_source_path
  22: git_filter_source_path
  23: git_filter_source_path
  24: git_odb_object_size
  25: git_filter_source_path
  26: cairo_raster_source_pattern_set_snapshot
  27: BaseThreadInitThunk
  28: RtlUserThreadStart

thread 'main' panicked at pty\src\cmdbuilder.rs:598:67:
byte index 1 is out of bounds of ``
stack backtrace:
   0:     0x7ff6747bc7a1 - git_odb_object_size
   1:     0x7ff6747e3caa - git_odb_object_size
   2:     0x7ff6747b6707 - git_odb_object_size
   3:     0x7ff6747bc5e5 - git_odb_object_size
   4:     0x7ff6747be8d5 - git_odb_object_size
   5:     0x7ff6747be6b5 - git_odb_object_size
   6:     0x7ff6730ff49f - git_filter_source_path
   7:     0x7ff6747befa2 - git_odb_object_size
   8:     0x7ff6747bede9 - git_odb_object_size
   9:     0x7ff6747bd25f - git_odb_object_size
  10:     0x7ff6747be9ee - git_odb_object_size
  11:     0x7ff674e2c6c1 - cairo_raster_source_pattern_set_snapshot
  12:     0x7ff6747e77f1 - git_odb_object_size
  13:     0x7ff674e2cdd8 - cairo_raster_source_pattern_set_snapshot
  14:     0x7ff6742c5e72 - git_odb_object_size
  15:     0x7ff6742cc55f - git_odb_object_size
  16:     0x7ff6742ce17a - git_odb_object_size
  17:     0x7ff673cd2be6 - git_patch_owner
  18:     0x7ff672f7ee1b - git_filter_source_path
  19:     0x7ff672fbaf25 - git_filter_source_path
  20:     0x7ff672f757d4 - git_filter_source_path
  21:     0x7ff672c21186 - <unknown>
  22:     0x7ff673eb7782 - git_odb_object_size
  23:     0x7ff673e8f3a0 - git_odb_object_size
  24:     0x7ff672f5639a - git_filter_source_path
  25:     0x7ff672f59467 - git_filter_source_path
  26:     0x7ff672f1e576 - git_filter_source_path
  27:     0x7ff6730605cc - git_filter_source_path
  28:     0x7ff6747adc9c - git_odb_object_size
  29:     0x7ff672f6579c - git_filter_source_path
  30:     0x7ff674db05d4 - cairo_raster_source_pattern_set_snapshot
  31:     0x7ffbdeb07374 - BaseThreadInitThunk
  32:     0x7ffbe02bcc91 - RtlUserThreadStart
```

The same issue (with the same exact stack trace) also affects the **20240623-130118-4daab4dc** nightly version.

_WezTerm_ w/o arguments (or whenever `config.default_prog` is set in `~/.wezterm.lua`) starts normally.

### Configuration

Can be reproduced even with an empty config ("no config").

```lua
local wezterm = require 'wezterm'

local config = {}

if wezterm.config_builder then
  config = wezterm.config_builder()
end

config.anti_alias_custom_block_glyphs = false
config.check_for_updates = false

config.colors = {
  foreground = '#c0c0c0',
  background = '#000000',
  selection_fg = '#3f3f3f',
  selection_bg = '#ffffff',
  ansi = {
    '#000000',
    '#800000',
    '#008000',
    '#808000',
    '#000080',
    '#800080',
    '#008080',
    '#c0c0c0',
  },
  brights = {
    '#808080',
    '#ff0000',
    '#00ff00',
    '#ffff00',
    '#0000ff',
    '#ff00ff',
    '#00ffff',
    '#ffffff',
  },
}

config.font = wezterm.font('Courier New')
config.font_size = 12
config.font_rules = {
  {
    intensity = 'Normal',
    italic = true,
    font = wezterm.font('Courier New', { italic = true })
  },
  {
    intensity = 'Bold',
    italic = false,
    font = wezterm.font('Courier New', { weight = 'Bold' })
  },
  {
    intensity = 'Bold',
    italic = true,
    font = wezterm.font('Courier New', { weight = 'Bold', italic = true })
  },
}
config.freetype_load_flags = 'NO_AUTOHINT|MONOCHROME'
config.freetype_load_target = 'Mono'

config.hide_tab_bar_if_only_one_tab = true
config.initial_cols = 80
config.initial_rows = 24
config.window_frame = {
  border_bottom_height = '0cell',
  border_left_width = '0cell',
  border_right_width = '0cell',
  border_top_height = '0cell',
}

return config
```

### Logs

```console
Debug Overlay
wezterm version: 20241205-083533-6f375e29 x86_64-pc-windows-msvc
Window Environment: Windows
Lua Version: Lua 5.4
OpenGL: Intel(R) UHD Graphics 770 4.5.0 - Build 32.0.101.6319
Enter lua statements or expressions and hit Enter.
Press ESC or CTRL-D to exit
```

The built-in Lua interpreter works fine (e.g.: `print ("Hello World!")` indeed logs the line to the screen and the log file).

### Anything else?

I have recently installed Lua interpreters (**5.1** and **5.4**, 64-bit), but removing `lua54.dll` from the `PATH` doesn't change anything.

**Comment by 0x6675636b796f75676974687562** [comment]
Also, I have a concern about using `std::env::split_paths` to split `PATHEXT`. The `PATHEXT` environment variable is not a list of paths separated by platform-specific path separators (like `;` on Windows). Instead, it's a _semicolon_-separated list of file extensions (e.g., `.EXE;.COM;.BAT`).

Using `std::env::split_paths` here seems incorrect because it interprets the semicolon-separated `PATHEXT` as if it were a `PATH`, potentially leading to unexpected results (because, for instance, this call also [_performs unquoting on Windows_](https://doc.rust-lang.org/std/env/fn.split_paths.html), will panic if there's no `PATH`, and may have extra side effects in the future). Instead, I'd consider splitting `PATHEXT` using a simple semicolon separator (`;`), e.g:

```rust
if let Some(path) = self.get_env("PATH") {
    let extensions = self.get_env("PATHEXT").unwrap_or(OsStr::new(".EXE"));
    for path in std::env::split_paths(&path) {
        let candidate = path.join(&exe);
        if candidate.exists() {
            return candidate.into_os_string();
        }

        // Correctly split PATHEXT by semicolons.
        if let Some(exts) = extensions.to_str() {
            for ext in exts.split(';') {
                if ext.is_empty() {
                    continue;
                }
                let path = path.join(&exe).with_extension(&ext.trim_start_matches('.'));
                if path.exists() {
                    return path.into_os_string();
                }
            }
        }
    }
}
```

**Comment by wez** [comment]
Thanks for investigating this; would you like to submit a PR to resolve this?
