### ISSUE TITLE
Crash when selecting text

### ISSUE THREAD

**Issue by simpoir** [wez/wezterm#713]
## Describe the bug

Crash while selecting text in word-selection mode and moving the mouse out of the window boundaries.

## Environment (please complete the following information):

 - OS: Linux X11, bspwm
 - Version: wezterm 20210405-110924-a5bb5be8
 - The active keyboard layout name: us (mac)

## To Reproduce

- in a new terminal
- double-click and hold, in order to start word-bound text selection
- while holding left mouse button to select text, drag mouse outside of the window
- crash

Crash can occur on any of the window 4 sides.
Simple selection (just mouse down) or line selection (triple click+hold) don't seem affected. 
If there is scrollable content in the terminal, the bug only triggers if you scroll to the top/bottom of the backlog.

## Expected behavior

Not crashing.

## Additional context

 2021-04-20T22:16:55.750Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-917438
 2021-04-20T22:16:56.012Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) HD Graphics 620 (KBL GT2) OpenGL ES 3.2 Mesa 20.2.6 is_context_loss_possible=false wezterm version: 20210405-110924-a5bb5be8
thread 'main' panicked at 'x=18446744073709551615 is outside of this logical line of len 105', mux/src/pane.rs:111:9

**Comment by wez** [comment]
Please try a nightly build!

**Comment by simpoir** [comment]
Thanks!
That's actually an improvement (20210405-110924-a5bb5be8-105-ge9372086).
Horizontally doesn't crash on nightly, but still does when selecting vertically (on both top and bottom edges) 

 2021-04-21T01:50:57.307Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-1001291
 2021-04-21T01:50:57.384Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) HD Graphics 620 (KBL GT2) OpenGL ES 3.2 Mesa 20.2.6 is_context_loss_possible=false wezterm version: 20210405-110924-a5bb5be8-105-ge9372086
thread 'main' panicked at 'x=37 y=21 is outside of this logical line starting at 0 comprised of 1 physical lines', mux/src/pane.rs:95:9
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by brymko** [comment]
Not sure if you mixed horizontally with vertically as the current git build crashes vertically, but not horizontally, for me.
replacing this panic https://github.com/wez/wezterm/blob/0ed94a4218b634ff6d72f58a234323493a5d9632/mux/src/pane.rs#L95 with `offset + x` gives the desired behaviour.

**Comment by wez** [comment]
Thanks for reporting this; this should be fixed in the next nightly build! (~30 minutes or so)
