### ISSUE TITLE
Build failed on Windows, perl and/or openssl problem?

### ISSUE THREAD

**Issue by kaddkaka** [wez/wezterm#731]
## Build Environment:

 - OS: Windows 10 Enterprise Version 1809
 - Git bash terminal (MINGW64)
 - Rust version: 
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\mtk11578\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

## Dependencies
I ran `get-deps` and there was no output at all, so I assumed it was successful.

## The build output
The first time I ran the cargo `build --release` I hit an error that prompted me to install visual studio build tools - done.
So I ran `cargo build --release` again and it failed on `openssl-sys` with the output:
```
error: failed to run custom build command for `openssl-sys v0.9.61`

Caused by:
  process didn't exit successfully: `C:\Users\david\git\wezterm\target\release\build\openssl-sys-8b8475d1e73380df\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\david\\git\\wezterm\\target\\release\\build\\openssl-sys-70974a82ea11a170\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"
  Configuring OpenSSL version 1.1.1k (0x101010bfL) for VC-WIN64A
  Using os-specific seed configuration

  --- stderr

  ******************************************************************************
  This perl implementation doesn't produce Windows like paths (with backward
  slash directory separators).  Please use an implementation that matches your
  building platform.

  This Perl version: 5.32.1 for x86_64-msys-thread-multi
  ******************************************************************************
  thread 'main' panicked at '


  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=C:\\Users\\david\\git\\wezterm\\target\\release\\build\\openssl-sys-70974a82ea11a170\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"
      Exit status: exit code: 127


      ', C:\Users\david\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.15.0+1.1.1k\src\lib.rs:471:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I figured I just try the `cargo build --release` command  again and got a slightly different error:

```
error: failed to run custom build command for `openssl-sys v0.9.61`

Caused by:
  process didn't exit successfully: `C:\Users\mtk11578\git\wezterm\target\release\build\openssl-sys-8b8475d1e73380df\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }', C:\Users\mtk11578\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.15.0+1.1.1k\src\lib.rs:123:44
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

The backtrace is 
```
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\std\src\panicking.rs:493
     1: core::panicking::panic_fmt
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\panicking.rs:92
     2: core::option::expect_none_failed
               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\/library\core\src\option.rs:1300
     3: core::result::Result<T,E>::unwrap
     4: openssl_src::Build::build
     5: build_script_main::find_vendored::get_openssl
     6: build_script_main::env::{{closure}}
     7: build_script_main::find_openssl::{{closure}}
     8: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by wez** [comment]
You need [strawberry perl](https://strawberryperl.com/) to build openssl on windows

**Comment by wez** [comment]
I think this is resolved based on conversation in the matrix room, so closing!

**Comment by rRaDuCaN** [comment]
a better alternative would be to install OpenSSL through chocolatey `choco install openssl`
