### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 48 but the index is 48', termwiz/src/surface/line.rs:326:9

### ISSUE THREAD

**Issue by brymko** [wez/wezterm#768]
## Describe the bug

terminal crashes under some! specific circumstances. I've first obvserved this bug while debugging with gdb in a docker container. When i tried to report it the first time i couldn't reproduce it reliable. Today i found to reliable crash the terminal by connecting via ssh to my server and running `tmux a`. Here is a full stack trace:

```
thread 'main' panicked at 'index out of bounds: the len is 48 but the index is 48', termwiz/src/surface/line.rs:326:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:69:5
   3: termwiz::surface::line::Line::set_cell
   4: wezterm_term::screen::Screen::set_cell
   5: wezterm_term::terminalstate::Performer::flush_print
   6: wezterm_term::terminalstate::Performer::perform
   7: wezterm_term::terminal::Terminal::perform_actions
   8: <mux::localpane::LocalPane as mux::pane::Pane>::perform_actions
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: async_task::raw::RawTask<F,T,S>::run
  11: window::spawn::SpawnQueue::run
  12: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
  13: wezterm_gui::run
  14: wezterm_gui::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'task has failed', /home/brymko/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/option.rs:1321:5
   3: <async_task::task::Task<T> as core::future::future::Future>::poll
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: async_io::driver::block_on
   6: std::thread::local::LocalKey<T>::with
   7: async_std::task::builder::Builder::blocking
   8: mux::parse_buffered_data
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/07e0e2ec268c140e607e1ac7f49f145612d0f597/library/core/src/option.rs:1329:5
   3: mux::BufState::write
   4: mux::read_from_pane_pty
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Environment (please complete the following information):

 - Linux X11
 - wezterm 20210503-220535-d64b7852
 - US ANSI

## To Reproduce

This probably? cause by an invisible glyph?. This is also weird as the terminal can clearly display the text if tmux is already open in a patched terminal, but the second i close it the terminal crashes. I've pinpointed the crash according to this code snipped https://github.com/wez/wezterm/blob/d64b785290dddff5bf76a82faf8dbe53f159be4b/termwiz/src/surface/line.rs#L310
If the width is 0 this will cause an off by one in the allocation if `idx == self.cells.len()`. 
By patching the resizing to this `self.cells.resize(idx + width + 1, Cell::default());` I was not able to reproduce the crash anymore.

**Comment by wez** [comment]
Interesting.  Would you mind logging the cell in that case?  `log::info!("cell: {:#?}", cell)` so that we can see what is inside it?

**Comment by wez** [comment]
Thanks!  I believe that this is now resolved in the nightly build!
