### ISSUE TITLE
Crashing due to unknown escape sequence 

### ISSUE THREAD

**Issue by SuperSandro2000** [wez/wezterm#812]
## Describe the bug

I have some character in my history which crashes wezterm when displayed.

## Environment (please complete the following information):

 - OS: Windows
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: DE

## To Reproduce

- Connect from WSL to Linux machine
- ``echo ``
- Ctrl + R in fzf

## Configuration

```
local wezterm = require 'wezterm';
return {
  color_scheme = "Gruvbox Dark",
  default_prog = {"wsl.exe"},
  font = wezterm.font_with_fallback({"JetBrains Mono", "Symbols Nerd Font"}),
  font_size = 13.5,
  hide_tab_bar_if_only_one_tab = false,
  hyperlink_rules = {
    -- Linkify things that look like URLs
    -- This is actually the default if you don't specify any hyperlink_rules
    {regex = "\\b\\w+://(?:[\\w.-]+)\\.[a-z]{2,15}\\S*\\b", format = "$0"}, -- linkify email addresses
    {regex = "\\b\\w+@[\\w-]+(\\.[\\w-]+)+\\b", format = "mailto:$0"}, -- file:// URI
....
....
....
    -- Make task numbers clickable
    --[[
    {
      regex = "\\b[tT](\\d+)\\b"
      format = "https://example.com/tasks/?t=$1"
    }
    ]]
  },
  keys = {
    -- because of some bug Tab is detect as i
    {key = "raw:9", mods = "CTRL|SHIFT", action = wezterm.action {ActivateTabRelative = -1}},
    {key = "raw:9", mods = "CTRL", action = wezterm.action {ActivateTabRelative = 1}}
  },
  launch_menu = {{args = {"cmd.exe"}, label = "cmd"}},
  text_background_opacity = 1.0,
  window_background_opacity = 0.9
}

```

## Expected behavior
Not crash.

## Log

```
 2021-05-21T17:04:11.466Z INFO  wezterm_mux_server_impl::local > setting up C:\Users\user\.local/share/wezterm\gui-sock-58596
 2021-05-21T17:04:11.673Z INFO  wezterm_gui::termwindow        > OpenGL initialized! ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0) OpenGL ES 3.0.0 (ANGLE 2.1.1 git hash: 07ea804e6201) is_context_loss_possible=true wezterm version: 20210502-154244-3f7122cb
 2021-05-21T17:04:14.179Z WARN  wezterm_term::terminalstate    > unhandled ControlCode StartOfHeading
 2021-05-21T17:04:14.179Z WARN  wezterm_term::terminalstate    > unhandled ControlCode StartOfText
thread 'main' panicked at 'index out of bounds: the len is 31 but the index is 31', termwiz\src\surface\line.rs:326:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0\library\std\src\thread\local.rs:248:26
```

**Comment by wez** [comment]
Sounds like https://github.com/wez/wezterm/issues/768 which is fixed in the nightly builds

**Comment by SuperSandro2000** [comment]
Yeah, fixed. Thanks.
