### ISSUE TITLE
WezTerm crash on `cat` on a particular file.

### ISSUE THREAD

**Issue by rentruewang** [wez/wezterm#840]
## Describe the bug

WezTerm crashes on `cat` on a particular [file][file]. Please extract the file into `Android.log` before use.

Running `cat` on the file makes WezTerm crash. This procedure works fine in [Alacritty][alacritty].

Error message on Ubuntu:

With command `wezterm`:
```log
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 9', termwiz/src/surface/line.rs:326:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'task has failed', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
```

With command `RUST_BACKTRACE=full wezterm`:
```log
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 9', termwiz/src/surface/line.rs:326:9
stack backtrace:
   0:     0x55d7f6c82390 - <unknown>
   1:     0x55d7f6ca9edc - <unknown>
   2:     0x55d7f6c78f72 - <unknown>
   3:     0x55d7f6c84a85 - <unknown>
   4:     0x55d7f6c845e3 - <unknown>
   5:     0x55d7f6c85246 - <unknown>
   6:     0x55d7f6c84d67 - <unknown>
   7:     0x55d7f6c8282c - <unknown>
   8:     0x55d7f6c84cc9 - <unknown>
   9:     0x55d7f6ca7bb1 - <unknown>
  10:     0x55d7f6ca7b72 - <unknown>
  11:     0x55d7f69b99c3 - <unknown>
  12:     0x55d7f6885b81 - <unknown>
  13:     0x55d7f6836a4c - <unknown>
  14:     0x55d7f6836f0a - <unknown>
  15:     0x55d7f68817ad - <unknown>
  16:     0x55d7f640820c - <unknown>
  17:     0x55d7f6490934 - <unknown>
  18:     0x55d7f646c348 - <unknown>
  19:     0x55d7f650aa53 - <unknown>
  20:     0x55d7f650e799 - <unknown>
  21:     0x55d7f5d50813 - <unknown>
  22:     0x55d7f5d4dab7 - <unknown>
  23:     0x55d7f5cdcce3 - <unknown>
  24:     0x55d7f5de8b89 - <unknown>
  25:     0x55d7f6c85737 - <unknown>
  26:     0x55d7f5d52942 - <unknown>
  27:     0x7f95219a4cb2 - __libc_start_main
  28:     0x55d7f5c65f4e - <unknown>
  29:                0x0 - <unknown>
thread '<unnamed>' panicked at 'task has failed', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
stack backtrace:
   0:     0x55d7f6c82390 - <unknown>
   1:     0x55d7f6ca9edc - <unknown>
   2:     0x55d7f6c78f72 - <unknown>
   3:     0x55d7f6c84a85 - <unknown>
   4:     0x55d7f6c845e3 - <unknown>
   5:     0x55d7f6c85246 - <unknown>
   6:     0x55d7f6c84d67 - <unknown>
   7:     0x55d7f6c8282c - <unknown>
   8:     0x55d7f6c84cc9 - <unknown>
   9:     0x55d7f6ca7bb1 - <unknown>
  10:     0x55d7f6ca7943 - <unknown>
  11:     0x55d7f642903d - <unknown>
  12:     0x55d7f648d3bd - <unknown>
  13:     0x55d7f63d9473 - <unknown>
  14:     0x55d7f647a148 - <unknown>
  15:     0x55d7f64912da - <unknown>
  16:     0x55d7f641d156 - <unknown>
  17:     0x55d7f6423bab - <unknown>
  18:     0x55d7f6445eea - <unknown>
  19:     0x55d7f6c8eb5a - <unknown>
  20:     0x7f95215a9590 - start_thread
  21:     0x7f9521a95223 - clone
  22:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
stack backtrace:
   0:     0x55d7f6c82390 - <unknown>
   1:     0x55d7f6ca9edc - <unknown>
   2:     0x55d7f6c78f72 - <unknown>
   3:     0x55d7f6c84a85 - <unknown>
   4:     0x55d7f6c845e3 - <unknown>
   5:     0x55d7f6c85246 - <unknown>
   6:     0x55d7f6c84d67 - <unknown>
   7:     0x55d7f6c8282c - <unknown>
   8:     0x55d7f6c84cc9 - <unknown>
   9:     0x55d7f6ca7bb1 - <unknown>
  10:     0x55d7f6ca79d3 - <unknown>
  11:     0x55d7f641cdbb - <unknown>
  12:     0x55d7f641d78a - <unknown>
  13:     0x55d7f6423b7f - <unknown>
  14:     0x55d7f6445be8 - <unknown>
  15:     0x55d7f6c8eb5a - <unknown>
  16:     0x7f95215a9590 - start_thread
  17:     0x7f9521a95223 - clone
  18:                0x0 - <unknown>
```

Error message on MacOS:

With command `wezterm`:
```log
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 9', termwiz/src/surface/line.rs:326:9
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
thread '<unnamed>' panicked at 'task has failed', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:26
fatal runtime error: failed to initiate panic, error 5
```

With command `RUST_BACKTRACE=full wezterm`:
```log
thread 'main' panicked at 'index out of bounds: the len is 9 but the index is 9', termwiz/src/surface/line.rs:326:9
stack backtrace:
   0:        0x10af07af4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10af2a2fd - core::fmt::write::h24f8349e8e89c9af
   2:        0x10aefed56 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x10af09e99 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x10af09a29 - std::panicking::default_hook::he168e99d1cf91c3c
   5:        0x10af0a53e - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   6:        0x10af0a045 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   7:        0x10af07f98 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   8:        0x10af09faa - _rust_begin_unwind
   9:        0x10af6fcdf - core::panicking::panic_fmt::habd0855285375977
  10:        0x10af6fca6 - core::panicking::panic_bounds_check::he5e20866df707d5e
  11:        0x10ab78b8d - termwiz::surface::line::Line::set_cell::hcfb7dc69111486e8
  12:        0x10aa52a65 - wezterm_term::screen::Screen::set_cell::hfaf0f32c2e887a2c
  13:        0x10a9ee622 - wezterm_term::terminalstate::Performer::flush_print::h58e054c746705aac
  14:        0x10a9eeaa0 - wezterm_term::terminalstate::Performer::perform::h8f6ccee3ba000623
  15:        0x10aa4e718 - wezterm_term::terminal::Terminal::perform_actions::h23cab701a7e87fd0
  16:        0x10a628597 - <mux::localpane::LocalPane as mux::pane::Pane>::perform_actions::h633e70e46ee3ef26
  17:        0x10a5eb177 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hd3d24cd25cb3c466
  18:        0x10a5ce126 - async_task::raw::RawTask<F,T,S>::run::hb21a10ea90274177
  19:        0x10a72e3d1 - window::spawn::SpawnQueue::run::hdeb878cf720b0211
  20:        0x10a72e6f0 - window::spawn::SpawnQueue::trigger::h66ceb87bc385965c
  21:     0x7fff20725e41 - <unknown>
  22:     0x7fff20725cd5 - <unknown>
  23:     0x7fff20725496 - <unknown>
  24:     0x7fff2072475c - <unknown>
  25:     0x7fff28946203 - <unknown>
  26:     0x7fff28945f65 - <unknown>
  27:     0x7fff28945d03 - <unknown>
  28:     0x7fff22f20b32 - <unknown>
  29:     0x7fff22f1f305 - <unknown>
  30:     0x7fff22f11679 - <unknown>
  31:        0x10a72abc6 - <window::os::macos::connection::Connection as window::connection::ConnectionOps>::run_message_loop::h54fdb13bae027f1f
  32:        0x10a0181c1 - wezterm_gui::run::h0ee17056ae0541d4
  33:        0x10a015402 - wezterm_gui::main::h03355ecfc03ea067
  34:        0x109fbc9aa - std::sys_common::backtrace::__rust_begin_short_backtrace::h31c12490650e5bdd
  35:        0x10a09dd0c - std::rt::lang_start::{{closure}}::h09cb5ea809249110
  36:        0x10af0a974 - std::rt::lang_start_internal::h86f505dc7de50d93
  37:        0x10a01a469 - _main
thread '<unnamed>' panicked at 'task has failed', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
stack backtrace:
   0:        0x10af07af4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10af2a2fd - core::fmt::write::h24f8349e8e89c9af
   2:        0x10aefed56 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x10af09e99 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x10af09a29 - std::panicking::default_hook::he168e99d1cf91c3c
   5:        0x10af0a53e - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   6:        0x10af0a045 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   7:        0x10af07f98 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   8:        0x10af09faa - _rust_begin_unwind
   9:        0x10af6fcdf - core::panicking::panic_fmt::habd0855285375977
  10:        0x10af6fb6a - core::option::expect_failed::hb462c55ae9fcb5c3
  11:        0x10a64b726 - <async_task::task::Task<T> as core::future::future::Future>::poll::h9d23b62af40795c3
  12:        0x10a5e95e3 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h90fed4a781f4a2ae
  13:        0x10a5fc5cf - async_io::driver::block_on::h90e8c7a169112c75
  14:        0x10a5d6328 - std::thread::local::LocalKey<T>::with::h96310f6ee45dc6e4
  15:        0x10a5ec95c - async_std::task::builder::Builder::blocking::h6a0ca2a12fafcad8
  16:        0x10a63ff49 - mux::parse_buffered_data::h2c9c24471466d470
  17:        0x10a6675ad - std::sys_common::backtrace::__rust_begin_short_backtrace::h4da2736ca5c38d24
  18:        0x10a66d2e9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfc3c019e98ee03e7
  19:        0x10af12c3d - std::sys::unix::thread::Thread::new::thread_start::ha736b2d9de7b4dbc
  20:     0x7fff2062d954 - __pthread_start
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
stack backtrace:
   0:        0x10af07af4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10af2a2fd - core::fmt::write::h24f8349e8e89c9af
   2:        0x10aefed56 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x10af09e99 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x10af09a29 - std::panicking::default_hook::he168e99d1cf91c3c
   5:        0x10af0a53e - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   6:        0x10af0a045 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   7:        0x10af07f98 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   8:        0x10af09faa - _rust_begin_unwind
   9:        0x10af6fcdf - core::panicking::panic_fmt::habd0855285375977
  10:        0x10af6fbe5 - core::result::unwrap_failed::hbb3d99b969dfb539
  11:        0x10a63fb8e - mux::BufState::write::hab23db0e8eaed6b9
  12:        0x10a640567 - mux::read_from_pane_pty::hd86c92a62d3bffc6
  13:        0x10a66757b - std::sys_common::backtrace::__rust_begin_short_backtrace::h1a630354a9a2b785
  14:        0x10a66ce1e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h651ae5ce9057ce2f
  15:        0x10af12c3d - std::sys::unix::thread::Thread::new::thread_start::ha736b2d9de7b4dbc
  16:     0x7fff2062d954 - __pthread_start
thread '<unnamed>' panicked at 'cannot access a Thread Local Storage value during or after destruction: AccessError', /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/thread/local.rs:248:26
stack backtrace:
   0:        0x10af07af4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h18cc31b07c2f1a67
   1:        0x10af2a2fd - core::fmt::write::h24f8349e8e89c9af
   2:        0x10aefed56 - std::io::Write::write_fmt::hc54d7d6e95b15753
   3:        0x10af09e99 - std::panicking::default_hook::{{closure}}::h11b550d560f5cc66
   4:        0x10af09a29 - std::panicking::default_hook::he168e99d1cf91c3c
   5:        0x10af0a53e - std::panicking::rust_panic_with_hook::hf87bfc4afef21ea6
   6:        0x10af0a045 - std::panicking::begin_panic_handler::{{closure}}::h19ac9cd24a19b238
   7:        0x10af07f98 - std::sys_common::backtrace::__rust_end_short_backtrace::h5fc3f41df3517232
   8:        0x10af09faa - _rust_begin_unwind
   9:        0x10af6fcdf - core::panicking::panic_fmt::habd0855285375977
  10:        0x10af6fbe5 - core::result::unwrap_failed::hbb3d99b969dfb539
  11:        0x10a7338b1 - window::connection::shutdown::h2308bf1dde31dffc
  12:        0x109fd072f - std::thread::local::fast::destroy_value::h049e7702ee654bc1
  13:        0x10af12f9c - std::sys::unix::thread_local_dtor::register_dtor::run_dtors::h265caa226728bb6f
  14:     0x7fff20647e18 - <unknown>
  15:     0x7fff2055d019 - <unknown>
fatal runtime error: failed to initiate panic, error 5
```

## Environment

 - OS: Ubuntu 20.10 and MacOS 11.3.1
 - Version: wezterm 20210502-154244-3f7122cb
 - Keyboard layout: en_US

## To Reproduce

1. Luanch WezTerm in a terminal.
2. Download and extract this [file][file].
3. Run `cat` on the extracted `Android.log`.

## Configuration

```lua
local wezterm = require 'wezterm';

return {
  font = wezterm.font("Fira Code"),
};
```

## Expected behavior

Instead of crashing, WezTerm should display the content of the file.

[file]: https://zenodo.org/record/3227177/files/Android.tar.gz
[alacritty]: https://github.com/alacritty/alacritty

**Comment by bew** [comment]
This looks like #768, which has been resolved in nightly' version

**Comment by rentruewang** [comment]
@bew Yes it does! Thanks!
