### ISSUE TITLE
Crash: `removal index (is 110) should be < len (is 110)`

### ISSUE THREAD

**Issue by jsgf** [wez/wezterm#847]
## Describe the bug

While using wezterm in multiplex mode, the client suddenly crashed with 
```
thread 'main' panicked at 'removal index (is 110) should be < len (is 110)', library/alloc/src/vec/mod.rs:1347:13
```

## Environment (please complete the following information):

 - OS: Linux X11
 - Version: wezterm 20210529-194808-27fa3436 based on 529b709277a476f4ee0f3b9e87c9b0bd49f0c25d
 - The active keyboard layout name: ENG

## To Reproduce

Unclear - happens sporadically.

Running:
- `wezterm-mux-server` on a remote machine
- `wezterm connect <host>` on a local machine

 The most recent time I was just editing a command line, though I'm not sure what was happening in the other tabs.

## Configuration

https://gist.github.com/jsgf/c46285121b14ba8197cf96fd6e6e0ded

## Expected behavior
Not crash

## Additional context
There were no log messages leading up to the crash, but I was running with RUST_BACKTRACE=1. Unfortunately the result is pretty useless without symbol info. I'll rebuild with debug.
```
thread 'main' panicked at 'removal index (is 110) should be < len (is 110)', library/alloc/src/vec/mod.rs:1347:13
stack backtrace:
   0:     0x55dfea16c040 - <unknown>
   1:     0x55dfea1923ef - <unknown>
   2:     0x55dfea1638b2 - <unknown>
   3:     0x55dfea16e755 - <unknown>
   4:     0x55dfea16e203 - <unknown>
   5:     0x55dfea16ed80 - <unknown>
   6:     0x55dfea16e8f7 - <unknown>
   7:     0x55dfea16c4fc - <unknown>
   8:     0x55dfea16e859 - <unknown>
   9:     0x55dfe91c5111 - <unknown>
  10:     0x55dfe91c4e86 - <unknown>
  11:     0x55dfe9ec6597 - <unknown>
  12:     0x55dfe979afd6 - <unknown>
  13:     0x55dfe979b2d6 - <unknown>
  14:     0x55dfe97dd4fa - <unknown>
  15:     0x55dfe9236c6a - <unknown>
  16:     0x55dfe922ba90 - <unknown>
  17:     0x55dfe92f94c5 - <unknown>
  18:     0x55dfe91cd65e - <unknown>
  19:     0x55dfe9a4eec0 - <unknown>
  20:     0x55dfe9a64190 - <unknown>
  21:     0x55dfe929240d - <unknown>
  22:     0x55dfe928e867 - <unknown>
  23:     0x55dfe91e0cf3 - <unknown>
  24:     0x55dfe93000a9 - <unknown>
  25:     0x55dfea16f25a - <unknown>
  26:     0x55dfe9293142 - <unknown>
  27:     0x7f060b0b7b75 - __libc_start_main
  28:     0x55dfe91c581e - <unknown>
  29:                0x0 - <unknown>
```

**Comment by jsgf** [comment]
Got a crash with symbols:
```
 2021-06-02T22:38:30.633Z INFO  wezterm_gui::termwindow > clicking https://phabricator.intern.facebook.com/D22857035
thread 'main' panicked at 'removal index (is 16) should be < len (is 16)', library/alloc/src/vec/mod.rs:1347:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: alloc::vec::Vec<T,A>::remove::assert_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/alloc/src/vec/mod.rs:1347:13
   3: alloc::vec::Vec<T,A>::remove
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:1352:13
   4: termwiz::surface::line::Line::erase_cell
             at ./termwiz/src/surface/line.rs:395:9
   5: wezterm_client::pane::renderable::RenderableInner::apply_prediction
             at ./wezterm-client/src/pane/renderable.rs:181:21
   6: wezterm_client::pane::renderable::RenderableInner::predict_from_key_event
             at ./wezterm-client/src/pane/renderable.rs:230:17
   7: <wezterm_client::pane::clienttab::ClientPane as mux::pane::Pane>::key_down
             at ./wezterm-client/src/pane/clienttab.rs:277:13
   8: wezterm_gui::termwindow::keyevent::<impl wezterm_gui::termwindow::TermWindow>::key_event_impl::{{closure}}
             at ./wezterm-gui/src/termwindow/keyevent.rs:212:24
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  10: wezterm_gui::termwindow::TermWindow::dispatch_window_event::{{closure}}
             at ./wezterm-gui/src/termwindow/mod.rs:656:17
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  12: wezterm_gui::termwindow::TermWindow::new_window::{{closure}}::{{closure}}
             at ./wezterm-gui/src/termwindow/mod.rs:557:31
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  14: <async_task::runnable::spawn_local::Checked<F> as core::future::future::Future>::poll
             at /home/jsgf/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/runnable.rs:132:22
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/future.rs:119:9
  16: async_task::raw::RawTask<F,T,S>::run
             at /home/jsgf/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/raw.rs:489:20
  17: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1546:9
  18: window::spawn::SpawnQueue::run_impl
             at ./window/src/spawn.rs:171:13
  19: window::spawn::SpawnQueue::run
             at ./window/src/spawn.rs:65:9
  20: <window::os::x11::connection::XConnection as window::connection::ConnectionOps>::run_message_loop
             at ./window/src/os/x11/connection.rs:183:16
  21: wezterm_gui::frontend::GuiFrontEnd::run_forever
             at ./wezterm-gui/src/frontend.rs:87:9
  22: wezterm_gui::run_mux_client
             at ./wezterm-gui/src/main.rs:247:5
  23: wezterm_gui::run
             at ./wezterm-gui/src/main.rs:541:41
  24: wezterm_gui::main
             at ./wezterm-gui/src/main.rs:402:21
  25: core::ops::function::FnOnce::call_once
             at /home/jsgf/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jsgf** [comment]
Using `vi` seems to make it happen very easily.
