### ISSUE TITLE
Crash When Displaying String with U+200E LEFT-TO-RIGHT MARK

### ISSUE THREAD

**Issue by dwmunster** [wez/wezterm#868]
## Describe the bug

Outputting a string containing the [U+200E LEFT-TO-RIGHT MARK](https://codepoints.net/U+200E) causes the terminal to crash.

## Environment (please complete the following information):

 - OS: Linux Xorg (Pop OS 20.10)
 - Version: wezterm 20210502-154244-3f7122cb
 - The active keyboard layout name: ENG

## To Reproduce

```bash
python -c "print('\u200e')"
```

## Configuration

Entirety of my configuration:

```lua
local wezterm = require 'wezterm';
return {
  font = wezterm.font("JetBrains Mono"),
}
```

## Expected behavior

For the terminal to not crash.

## Screenshots

N/A

## Session Recording

N/A

## Additional context

Output from running with `RUST_BACKTRACE=full`

```
2021-06-13T23:49:16.323Z INFO  wezterm_mux_server_impl::local > setting up /run/user/1000/wezterm/gui-sock-404509
2021-06-13T23:49:16.380Z INFO  wezterm_gui::termwindow        > OpenGL initialized! Mesa Intel(R) UHD Graphics (CML GT2) OpenGL ES 3.2 Mesa 21.0.0 is_context_loss_possible=false wezterm version: 20210502-154244-3f7122cb
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', termwiz/src/surface/line.rs:326:9
stack backtrace:
   0:     0x556fc508c390 - <unknown>
   1:     0x556fc50b3edc - <unknown>
   2:     0x556fc5082f72 - <unknown>
   3:     0x556fc508ea85 - <unknown>
   4:     0x556fc508e5e3 - <unknown>
   5:     0x556fc508f246 - <unknown>
   6:     0x556fc508ed67 - <unknown>
   7:     0x556fc508c82c - <unknown>
   8:     0x556fc508ecc9 - <unknown>
   9:     0x556fc50b1bb1 - <unknown>
  10:     0x556fc50b1b72 - <unknown>
  11:     0x556fc4dc39c3 - <unknown>
  12:     0x556fc4c8fb81 - <unknown>
  13:     0x556fc4c40a4c - <unknown>
  14:     0x556fc4c40f0a - <unknown>
  15:     0x556fc4c8b7ad - <unknown>
  16:     0x556fc481220c - <unknown>
  17:     0x556fc489a934 - <unknown>
  18:     0x556fc4876348 - <unknown>
  19:     0x556fc4914a53 - <unknown>
  20:     0x556fc4918799 - <unknown>
  21:     0x556fc415a813 - <unknown>
  22:     0x556fc4157ab7 - <unknown>
  23:     0x556fc40e6ce3 - <unknown>
  24:     0x556fc41f2b89 - <unknown>
  25:     0x556fc508f737 - <unknown>
  26:     0x556fc415c942 - <unknown>
  27:     0x7f0ef5667cb2 - __libc_start_main
  28:     0x556fc406ff4e - <unknown>
  29:                0x0 - <unknown>
thread '<unnamed>' panicked at 'task has failed', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-4.0.3/src/task.rs:368:45
stack backtrace:
   0:     0x556fc508c390 - <unknown>
   1:     0x556fc50b3edc - <unknown>
   2:     0x556fc5082f72 - <unknown>
   3:     0x556fc508ea85 - <unknown>
   4:     0x556fc508e5e3 - <unknown>
   5:     0x556fc508f246 - <unknown>
   6:     0x556fc508ed67 - <unknown>
   7:     0x556fc508c82c - <unknown>
   8:     0x556fc508ecc9 - <unknown>
   9:     0x556fc50b1bb1 - <unknown>
  10:     0x556fc50b1943 - <unknown>
  11:     0x556fc483303d - <unknown>
  12:     0x556fc48973bd - <unknown>
  13:     0x556fc47e3473 - <unknown>
  14:     0x556fc4884148 - <unknown>
  15:     0x556fc489b2da - <unknown>
  16:     0x556fc4827156 - <unknown>
  17:     0x556fc482dbab - <unknown>
  18:     0x556fc484feea - <unknown>
  19:     0x556fc5098b5a - <unknown>
  20:     0x7f0ef526c590 - start_thread
  21:     0x7f0ef5758223 - clone
  22:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', mux/src/lib.rs:89:43
stack backtrace:
   0:     0x556fc508c390 - <unknown>
   1:     0x556fc50b3edc - <unknown>
   2:     0x556fc5082f72 - <unknown>
   3:     0x556fc508ea85 - <unknown>
   4:     0x556fc508e5e3 - <unknown>
   5:     0x556fc508f246 - <unknown>
   6:     0x556fc508ed67 - <unknown>
   7:     0x556fc508c82c - <unknown>
   8:     0x556fc508ecc9 - <unknown>
   9:     0x556fc50b1bb1 - <unknown>
  10:     0x556fc50b19d3 - <unknown>
  11:     0x556fc4826dbb - <unknown>
  12:     0x556fc482778a - <unknown>
  13:     0x556fc482db7f - <unknown>
  14:     0x556fc484fbe8 - <unknown>
  15:     0x556fc5098b5a - <unknown>
  16:     0x7f0ef526c590 - start_thread
  17:     0x7f0ef5758223 - clone
  18:                0x0 - <unknown>
```

**Comment by dwmunster** [comment]
Issue is also present with longer strings when `U+200E` is present in the middle, in which case the error message mentions 

```
the len is N but the index is N
```
for the appropriate `N` value.

**Comment by wez** [comment]
Please try the nightly: a couple of bugs that sound like this have been fixed there

**Comment by dwmunster** [comment]
Issue is not present on `20210613-090629-c80cb73c`.
